modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="better_tools"
version="13.1"
displayName="Better Tools and Armor"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-tools-and-armor"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BlackCatGamer64, MCreator"
description="Adds many new ores and resources which improve the progression and exploration in Minecraft. Also adds many misc. features"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "better_tools.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.better_tools]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_tools]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.better_tools]]
    modId="curios_api"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="curios"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_tools]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration