package net.mcreator.bettertoolsandarmor;

import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.network.simple.SimpleChannel;
import net.minecraftforge.network.NetworkRegistry;
import net.minecraftforge.network.NetworkEvent;
import net.minecraftforge.fml.util.thread.SidedThreadGroups;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.network.chat.Component;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.core.registries.Registries;
import net.minecraft.client.renderer.Sheets;

import net.mcreator.bettertoolsandarmor.world.features.StructureFeature;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModWoodTypes;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModVillagerProfessions;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModTabs;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModSounds;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModPotions;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModParticleTypes;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModMobEffects;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModMenus;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModItems;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModFeatures;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModEntities;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModEnchantments;
import net.mcreator.bettertoolsandarmor.init.BetterToolsModBlocks;
import net.mcreator.bettertoolsandarmor.block.entity.BetterToolsModBlockEntities;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.List;
import java.util.Collection;
import java.util.ArrayList;
import java.util.AbstractMap;

@Mod("better_tools")
public class BetterToolsMod {
	public static final Logger LOGGER = LogManager.getLogger(BetterToolsMod.class);
	public static final String MODID = "better_tools";

	public BetterToolsMod() {
		// Start of user code block mod constructor
		MinecraftForge.EVENT_BUS.register(this);
		IEventBus bus2 = FMLJavaModLoadingContext.get().getModEventBus();
		BetterToolsModSounds.REGISTRY.register(bus2);
		BetterToolsModBlocks.REGISTRY.register(bus2);
		BetterToolsModItems.REGISTRY.register(bus2);
		BetterToolsModEntities.REGISTRY.register(bus2);
		BetterToolsModEnchantments.REGISTRY.register(bus2);
		BetterToolsModFeatures.REGISTRY.register(bus2);
		StructureFeature.REGISTRY.register(bus2);
		BetterToolsModMobEffects.REGISTRY.register(bus2);
		BetterToolsModPotions.REGISTRY.register(bus2);
		BetterToolsModParticleTypes.REGISTRY.register(bus2);
		BetterToolsModVillagerProfessions.PROFESSIONS.register(bus2);
		BetterToolsModMenus.REGISTRY.register(bus2);
		BetterToolsModTabsCustom.REGISTRY.register(bus2); // run custom creative tabs code
		if (false) { // skip generated init code
			// End of user code block mod constructor
			MinecraftForge.EVENT_BUS.register(this);
			IEventBus bus = FMLJavaModLoadingContext.get().getModEventBus();
			BetterToolsModSounds.REGISTRY.register(bus);
			BetterToolsModBlocks.REGISTRY.register(bus);
			BetterToolsModItems.REGISTRY.register(bus);
			BetterToolsModEntities.REGISTRY.register(bus);
			BetterToolsModEnchantments.REGISTRY.register(bus);
			BetterToolsModTabs.REGISTRY.register(bus);
			BetterToolsModFeatures.REGISTRY.register(bus);
			StructureFeature.REGISTRY.register(bus);
			BetterToolsModMobEffects.REGISTRY.register(bus);
			BetterToolsModPotions.REGISTRY.register(bus);
			BetterToolsModParticleTypes.REGISTRY.register(bus);
			BetterToolsModVillagerProfessions.PROFESSIONS.register(bus);
			BetterToolsModMenus.REGISTRY.register(bus);
			// Start of user code block mod init
		}
		BetterToolsModBlockEntities.REGISTRY.register(bus2);
		// End of user code block mod init
	}

	// Start of user code block mod methods
	@Mod.EventBusSubscriber(modid = MODID, bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientModEvents {
		@SubscribeEvent
		public static void onClientSetup(FMLClientSetupEvent event) {
			Sheets.addWoodType(BetterToolsModWoodTypes.BLACK_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.BLUE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.BROWN_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.CREAM_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.CYAN_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.DARK_RED_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.GRAY_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.GREEN_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.LIME_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.MAGENTA_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.ORANGE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.PINK_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.PURPLE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.RED_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.WHITE_METAL_SIGN);
			Sheets.addWoodType(BetterToolsModWoodTypes.YELLOW_METAL_SIGN);
		}
	}

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
	public class BetterToolsModTabsCustom {
		public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, BetterToolsMod.MODID);
		public static final RegistryObject<CreativeModeTab> BETTER_TOOLS_AND_ARMOR_MISC = REGISTRY.register("better_tools_and_armor_misc",
				() -> CreativeModeTab.builder().title(Component.translatable("item_group.better_tools.better_tools_and_armor_misc")).icon(() -> new ItemStack(BetterToolsModItems.CREATIVE_TAB_LOGO.get())).displayItems((parameters, tabData) -> {
					tabData.accept(BetterToolsModBlocks.SUGAR_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.RANDOM_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.DEEPSLATE_RANDOM_ORE.get().asItem());
					tabData.accept(BetterToolsModItems.MIXED_ESSENCE.get());
					tabData.accept(BetterToolsModItems.OBSIDIAN_STICK.get());
					tabData.accept(BetterToolsModBlocks.BLACKSTONE_MAGMA.get().asItem());
					tabData.accept(BetterToolsModBlocks.FOUR_LEAF_CLOVER.get().asItem());
					tabData.accept(BetterToolsModItems.BARK.get());
					tabData.accept(BetterToolsModItems.GUARDIAN_SPIKE.get());
					tabData.accept(BetterToolsModBlocks.PURPLE_MUSHROOM.get().asItem());
					tabData.accept(BetterToolsModBlocks.PURPLE_MUSHROOM_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.PURPLE_MOOSHROOM_SPAWN_EGG.get());
					tabData.accept(BetterToolsModBlocks.BLUE_MUSHROOM.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLUE_MUSHROOM_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.BLUE_SLIMEBALL.get());
					tabData.accept(BetterToolsModBlocks.BLUE_SLIME_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.BLUE_SLIME_STICK.get());
					tabData.accept(BetterToolsModItems.AMOGUS.get());
					tabData.accept(BetterToolsModItems.SUGAR_CLUMP.get());
					tabData.accept(BetterToolsModItems.GOLDEN_POTATO.get());
					tabData.accept(BetterToolsModItems.BERRY_PIE.get());
					tabData.accept(BetterToolsModItems.APPLE_JUICE.get());
					tabData.accept(BetterToolsModItems.BERRY_SMOOTHIE.get());
					tabData.accept(BetterToolsModItems.EXPERIENCE_POTION.get());
					tabData.accept(BetterToolsModItems.ASCENSION_POTION.get());
					tabData.accept(BetterToolsModItems.DESCENSION_POTION.get());
					tabData.accept(BetterToolsModItems.RECALL_POTION.get());
					tabData.accept(BetterToolsModItems.LOST_SOULS_POTION.get());
					tabData.accept(BetterToolsModItems.DIAMOND_APPLE.get());
					tabData.accept(BetterToolsModItems.FIRE_STAFF.get());
					tabData.accept(BetterToolsModItems.ICE_STAFF.get());
					tabData.accept(BetterToolsModItems.ELECTRIC_STAFF.get());
					tabData.accept(BetterToolsModItems.WARDEN_STAFF.get());
					tabData.accept(BetterToolsModItems.GUARDIAN_STAFF.get());
				}).build());
		public static final RegistryObject<CreativeModeTab> CRYSTALLITE_TAB = REGISTRY.register("crystallite_tab",
				() -> CreativeModeTab.builder().title(Component.translatable("item_group.better_tools.crystallite_tab")).icon(() -> new ItemStack(BetterToolsModItems.CRYSTALLITE_GEM.get())).displayItems((parameters, tabData) -> {
					tabData.accept(BetterToolsModBlocks.JEWELLERY_TABLE.get().asItem());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHARDS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_GEM.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_UPGRADE_SMITHING_TEMPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_CHARM_BASE.get());
					tabData.accept(BetterToolsModBlocks.CRYSTALLITE_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.CUT_CRYSTALLITE_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOOTS.get());
					tabData.accept(BetterToolsModItems.TOUGH_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.TOUGH_NECKLACE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_IRON.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_IRON_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_IRON_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_IRON_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_IRON_BOOTS.get());
					tabData.accept(BetterToolsModItems.GILDED_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.GILDED_BRACELET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_GOLD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_GOLD_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_GOLD_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_GOLD_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_GOLD_BOOTS.get());
					tabData.accept(BetterToolsModItems.MAGIC_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.MAGIC_RING.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_LAPIS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_LAPIS_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_LAPIS_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_LAPIS_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_LAPIS_BOOTS.get());
					tabData.accept(BetterToolsModItems.HEAL_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.HEART_CHARM.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_REDSTONE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_REDSTONE_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_REDSTONE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_REDSTONE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_REDSTONE_BOOTS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_HARD_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.DIAMOND_HARD_PLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_DIAMOND_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_DIAMOND_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_DIAMOND_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_DIAMOND_BOOTS.get());
					tabData.accept(BetterToolsModItems.SPIKED_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.WITHERED_GAUNTLET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_NETHERITE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHERITE_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHERITE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHERITE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHERITE_BOOTS.get());
					tabData.accept(BetterToolsModItems.SPEEDY_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.SPEEDY_NECKLACE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_RUBY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_RUBY_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_RUBY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_RUBY_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_RUBY_BOOTS.get());
					tabData.accept(BetterToolsModItems.ICE_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.ICY_BRACELET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_SAPPHIRE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SAPPHIRE_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SAPPHIRE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SAPPHIRE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SAPPHIRE_BOOTS.get());
					tabData.accept(BetterToolsModItems.ELECTRIC_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.ELECTRIC_NECKLACE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_TOPAZ.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_TOPAZ_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_TOPAZ_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_TOPAZ_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_TOPAZ_BOOTS.get());
					tabData.accept(BetterToolsModItems.FIRE_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.FLAMING_CIRCLET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHER_DIAMOND_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHER_DIAMOND_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHER_DIAMOND_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_NETHER_DIAMOND_BOOTS.get());
					tabData.accept(BetterToolsModItems.NATURE_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.NATURE_RING.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_EMERALD.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_EMERALD_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_EMERALD_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_EMERALD_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_EMERALD_BOOTS.get());
					tabData.accept(BetterToolsModItems.ECHO_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.WARDEN_HEADBAND.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_SCULK.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SCULK_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SCULK_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SCULK_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SCULK_BOOTS.get());
					tabData.accept(BetterToolsModItems.SKY_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.REFLECT_CHARM.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_SKY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SKY_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SKY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SKY_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_SKY_BOOTS.get());
					tabData.accept(BetterToolsModItems.EARTH_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.EARTH_CIRCLET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_AMETHYST.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_AMETHYST_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_AMETHYST_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_AMETHYST_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_AMETHYST_BOOTS.get());
					tabData.accept(BetterToolsModItems.GUARDIAN_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.GUARDIAN_NECKLACE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_PRISMARINE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_PRISMARINE_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_PRISMARINE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_PRISMARINE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_PRISMARINE_BOOTS.get());
					tabData.accept(BetterToolsModItems.HIVE_CRYSTAL.get());
					tabData.accept(BetterToolsModItems.CURING_CHARM.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SWORD_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_PICKAXE_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_AXE_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_SHOVEL_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_HOE_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_DAGGER_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_BOW_HONEY.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_HONEY_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_HONEY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_HONEY_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTALLITE_ARMOR_HONEY_BOOTS.get());
					tabData.accept(BetterToolsModItems.ENDER_GOGGLES.get());
					tabData.accept(BetterToolsModItems.BOUNCY_BRACELET.get());
					tabData.accept(BetterToolsModItems.POISON_CHARM.get());
					tabData.accept(BetterToolsModItems.LUCKY_CHARM.get());
				}).build());
		public static final RegistryObject<CreativeModeTab> TOOLS_AND_ARMOR_TAB = REGISTRY.register("tools_and_armor_tab",
				() -> CreativeModeTab.builder().title(Component.translatable("item_group.better_tools.tools_and_armor_tab")).icon(() -> new ItemStack(BetterToolsModItems.END_TITANIUM_PICKAXE.get())).displayItems((parameters, tabData) -> {
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND.get());
					tabData.accept(BetterToolsModBlocks.NETHER_DIAMOND_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.NETHER_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_SWORD.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_PICKAXE.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_AXE.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_SHOVEL.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_HOE.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_DAGGER.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_HELMET.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.NETHER_DIAMOND_BOOTS.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_SCRAP.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_INGOT.get());
					tabData.accept(BetterToolsModItems.ENDER_TITANIUM_UPGRADE_SMITHING_TEMPLATE.get());
					tabData.accept(BetterToolsModBlocks.END_TITANIUM_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.END_TITANIUM_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.END_TITANIUM_SWORD.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_PICKAXE.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_AXE.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_SHOVEL.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_HOE.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_DAGGER.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_HELMET.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.END_TITANIUM_BOOTS.get());
					tabData.accept(BetterToolsModItems.RUBY.get());
					tabData.accept(BetterToolsModBlocks.RUBY_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.DEEPSLATE_RUBY_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.RUBY_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.RUBY_SWORD.get());
					tabData.accept(BetterToolsModItems.RUBY_PICKAXE.get());
					tabData.accept(BetterToolsModItems.RUBY_AXE.get());
					tabData.accept(BetterToolsModItems.RUBY_SHOVEL.get());
					tabData.accept(BetterToolsModItems.RUBY_HOE.get());
					tabData.accept(BetterToolsModItems.RUBY_DAGGER.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE.get());
					tabData.accept(BetterToolsModBlocks.SAPPHIRE_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.SAPPHIRE_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.SAPPHIRE_SWORD.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_PICKAXE.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_AXE.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_SHOVEL.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_HOE.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_DAGGER.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_HELMET.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.SAPPHIRE_BOOTS.get());
					tabData.accept(BetterToolsModItems.TOPAZ.get());
					tabData.accept(BetterToolsModBlocks.TOPAZ_ORE.get().asItem());
					tabData.accept(BetterToolsModBlocks.TOPAZ_BLOCK.get().asItem());
					tabData.accept(BetterToolsModItems.TOPAZ_SWORD.get());
					tabData.accept(BetterToolsModItems.TOPAZ_PICKAXE.get());
					tabData.accept(BetterToolsModItems.TOPAZ_AXE.get());
					tabData.accept(BetterToolsModItems.TOPAZ_SHOVEL.get());
					tabData.accept(BetterToolsModItems.TOPAZ_HOE.get());
					tabData.accept(BetterToolsModItems.TOPAZ_DAGGER.get());
					tabData.accept(BetterToolsModItems.TOPAZ_HELMET.get());
					tabData.accept(BetterToolsModItems.TOPAZ_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.TOPAZ_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.TOPAZ_BOOTS.get());
					tabData.accept(BetterToolsModItems.FLINT_SWORD.get());
					tabData.accept(BetterToolsModItems.FLINT_PICKAXE.get());
					tabData.accept(BetterToolsModItems.FLINT_AXE.get());
					tabData.accept(BetterToolsModItems.FLINT_SHOVEL.get());
					tabData.accept(BetterToolsModItems.FLINT_HOE.get());
					tabData.accept(BetterToolsModItems.FLINT_DAGGER.get());
					tabData.accept(BetterToolsModItems.WOODEN_HELMET.get());
					tabData.accept(BetterToolsModItems.WOODEN_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.WOODEN_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.WOODEN_BOOTS.get());
					tabData.accept(BetterToolsModItems.WOOD_DAGGER.get());
					tabData.accept(BetterToolsModItems.STONE_DAGGER.get());
					tabData.accept(BetterToolsModItems.IRON_DAGGER.get());
					tabData.accept(BetterToolsModItems.GOLD_DAGGER.get());
					tabData.accept(BetterToolsModItems.DIAMOND_DAGGER.get());
					tabData.accept(BetterToolsModItems.NETHERITE_DAGGER.get());
					tabData.accept(BetterToolsModItems.BATTLE_AXE.get());
				}).build());
		public static final RegistryObject<CreativeModeTab> BLOCKS_TAB = REGISTRY.register("blocks_tab",
				() -> CreativeModeTab.builder().title(Component.translatable("item_group.better_tools.blocks_tab")).icon(() -> new ItemStack(BetterToolsModBlocks.DARK_POLISHED_IRON_BLOCK.get())).displayItems((parameters, tabData) -> {
					tabData.accept(BetterToolsModBlocks.CHARGED_ICE_ON.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.WHITE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.WHITE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_GRAY_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_GRAY_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.GRAY_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.GRAY_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLACK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLACK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_RED_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_RED_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.RED_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.RED_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_PINK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_PINK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.PINK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.PINK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLUE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLUE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.CYAN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.CYAN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_BLUE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_BLUE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIME_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIME_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.GREEN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.GREEN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BROWN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BROWN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_ORANGE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_ORANGE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.ORANGE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.ORANGE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.YELLOW_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.YELLOW_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.CREAM_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.CREAM_METAL_HANGING_SIGN.get().asItem());
				}).build());
		public static final RegistryObject<CreativeModeTab> EFFECT_ARMOR_TAB = REGISTRY.register("effect_armor_tab",
				() -> CreativeModeTab.builder().title(Component.translatable("item_group.better_tools.effect_armor_tab")).icon(() -> new ItemStack(BetterToolsModItems.CACTUS_CHESTPLATE.get())).displayItems((parameters, tabData) -> {
					tabData.accept(BetterToolsModItems.GOLD_CARROT_HELMET.get());
					tabData.accept(BetterToolsModItems.IRON_GOLD_CARROT_HELMET.get());
					tabData.accept(BetterToolsModItems.DIAMOND_GOLD_CARROT_HELMET.get());
					tabData.accept(BetterToolsModItems.CRYING_OBSIDIAN_HELMET.get());
					tabData.accept(BetterToolsModItems.DIAMOND_CRYING_OBSIDIAN_HELMET.get());
					tabData.accept(BetterToolsModItems.CACTUS_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.IRON_CACTUS_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.DIAMOND_CACTUS_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.HEARTY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.IRON_HEARTY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.DIAMOND_HEARTY_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.MAGMA_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.DIAMOND_MAGMA_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.RUBY_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_RUBY_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.CRYSTAL_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_CRYSTAL_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.BLACKSTONE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_BLACKSTONE_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.SUGAR_BOOTS.get());
					tabData.accept(BetterToolsModItems.IRON_SUGAR_BOOTS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_SUGAR_BOOTS.get());
					tabData.accept(BetterToolsModItems.RABBIT_BOOTS.get());
					tabData.accept(BetterToolsModItems.IRON_RABBIT_BOOTS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_RABBIT_BOOTS.get());
					tabData.accept(BetterToolsModItems.PHANTOM_BOOTS.get());
					tabData.accept(BetterToolsModItems.IRON_PHANTOM_BOOTS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_PHANTOM_BOOTS.get());
					tabData.accept(BetterToolsModItems.WINGED_BOOTS_BOOTS.get());
					tabData.accept(BetterToolsModItems.GLASS_HELMET.get());
					tabData.accept(BetterToolsModItems.GLASS_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.GLASS_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.GLASS_BOOTS.get());
					tabData.accept(BetterToolsModItems.IRON_GLASS_ARMOR_HELMET.get());
					tabData.accept(BetterToolsModItems.IRON_GLASS_ARMOR_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.IRON_GLASS_ARMOR_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.IRON_GLASS_ARMOR_BOOTS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_GLASS_ARMOR_HELMET.get());
					tabData.accept(BetterToolsModItems.DIAMOND_GLASS_ARMOR_CHESTPLATE.get());
					tabData.accept(BetterToolsModItems.DIAMOND_GLASS_ARMOR_LEGGINGS.get());
					tabData.accept(BetterToolsModItems.DIAMOND_GLASS_ARMOR_BOOTS.get());
				}).build());

		@SubscribeEvent
		public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
			if (tabData.getTabKey() == CreativeModeTabs.COMBAT) {
				tabData.accept(BetterToolsModItems.WOODEN_HELMET.get());
				tabData.accept(BetterToolsModItems.WOODEN_CHESTPLATE.get());
				tabData.accept(BetterToolsModItems.WOODEN_LEGGINGS.get());
				tabData.accept(BetterToolsModItems.WOODEN_BOOTS.get());
				tabData.accept(BetterToolsModItems.WOOD_DAGGER.get());
				tabData.accept(BetterToolsModItems.STONE_DAGGER.get());
				tabData.accept(BetterToolsModItems.IRON_DAGGER.get());
				tabData.accept(BetterToolsModItems.GOLD_DAGGER.get());
				tabData.accept(BetterToolsModItems.DIAMOND_DAGGER.get());
				tabData.accept(BetterToolsModItems.NETHERITE_DAGGER.get());
			} else if (tabData.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
				tabData.accept(BetterToolsModItems.SUGAR_CLUMP.get());
				tabData.accept(BetterToolsModItems.GOLDEN_POTATO.get());
				tabData.accept(BetterToolsModItems.BERRY_PIE.get());
				tabData.accept(BetterToolsModItems.APPLE_JUICE.get());
				tabData.accept(BetterToolsModItems.BERRY_SMOOTHIE.get());
				tabData.accept(BetterToolsModItems.DIAMOND_APPLE.get());
				tabData.accept(BetterToolsModItems.EXPERIENCE_POTION.get());
				tabData.accept(BetterToolsModItems.ASCENSION_POTION.get());
				tabData.accept(BetterToolsModItems.DESCENSION_POTION.get());
				tabData.accept(BetterToolsModItems.RECALL_POTION.get());
				tabData.accept(BetterToolsModItems.LOST_SOULS_POTION.get());
			}
		}
	}

	// End of user code block mod methods
	private static final String PROTOCOL_VERSION = "1";
	public static final SimpleChannel PACKET_HANDLER = NetworkRegistry.newSimpleChannel(new ResourceLocation(MODID, MODID), () -> PROTOCOL_VERSION, PROTOCOL_VERSION::equals, PROTOCOL_VERSION::equals);
	private static int messageID = 0;

	public static <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, FriendlyByteBuf> encoder, Function<FriendlyByteBuf, T> decoder, BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	private static final Collection<AbstractMap.SimpleEntry<Runnable, Integer>> workQueue = new ConcurrentLinkedQueue<>();

	public static void queueServerWork(int tick, Runnable action) {
		if (Thread.currentThread().getThreadGroup() == SidedThreadGroups.SERVER)
			workQueue.add(new AbstractMap.SimpleEntry<>(action, tick));
	}

	@SubscribeEvent
	public void tick(TickEvent.ServerTickEvent event) {
		if (event.phase == TickEvent.Phase.END) {
			List<AbstractMap.SimpleEntry<Runnable, Integer>> actions = new ArrayList<>();
			workQueue.forEach(work -> {
				work.setValue(work.getValue() - 1);
				if (work.getValue() == 0)
					actions.add(work);
			});
			actions.forEach(e -> e.getKey().run());
			workQueue.removeAll(actions);
		}
	}
}
