package net.mcreator.bettertoolsandarmor;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.mcreator.bettertoolsandarmor.init.BetterToolsModBlocks;

public class CustomCreativeTabItems {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, BetterToolsMod.MODID);
	public static final RegistryObject<CreativeModeTab> METAL_BLOCKS_TAB =
        REGISTRY.register("metal_blocks_tab", () ->
            CreativeModeTab.builder()
                .title(Component.translatable("item_group.better_tools.metal_blocks_tab"))
                .icon(() -> new ItemStack(BetterToolsModBlocks.DARK_POLISHED_IRON_BLOCK.get()))
                .displayItems((parameters, tabData) -> {
						tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_IRON_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.WHITE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.WHITE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_IRON_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_GRAY_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_GRAY_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COAL_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.GRAY_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.GRAY_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COAL_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLACK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLACK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_RUBY_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_RED_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_RED_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_REDSTONE_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.RED_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.RED_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_PINK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_PINK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.PINK_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.PINK_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.MAGENTA_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_AMETHYST_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.PURPLE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.PURPLE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_LAPIS_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLUE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BLUE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.CYAN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.CYAN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_DIAMOND_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_BLUE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_BLUE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIME_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIME_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_EMERALD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.GREEN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.GREEN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_POLISHED_COPPER_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.BROWN_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.BROWN_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_ORANGE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.DARK_ORANGE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_TOPAZ_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.ORANGE_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.ORANGE_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.POLISHED_GOLD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.YELLOW_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.YELLOW_METAL_HANGING_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_BLOCK.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_SLAB.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_STAIRS.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_WALL.get().asItem());
					tabData.accept(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_TRAPDOOR.get().asItem());
					tabData.accept(BetterToolsModBlocks.CREAM_METAL_SIGN.get().asItem());
					tabData.accept(BetterToolsModBlocks.CREAM_METAL_HANGING_SIGN.get().asItem());
                })
                .build());
}
