/*
*    MCreator note: This file will be REGENERATED on each build.
*/
package net.mcreator.bettertoolsandarmor.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SignItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.HangingSignItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.bettertoolsandarmor.procedures.EnergyVialEnergyValueProcedure;
import net.mcreator.bettertoolsandarmor.procedures.EnergyVialActiveProcedure;
import net.mcreator.bettertoolsandarmor.procedures.CrystalliteBowPullStateProcedure;
import net.mcreator.bettertoolsandarmor.item.*;
import net.mcreator.bettertoolsandarmor.BetterToolsMod;

public class BetterToolsModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(BetterToolsMod.MODID);
	public static final DeferredItem<Item> NETHER_DIAMOND;
	public static final DeferredItem<Item> NETHER_DIAMOND_SWORD;
	public static final DeferredItem<Item> NETHER_DIAMOND_PICKAXE;
	public static final DeferredItem<Item> NETHER_DIAMOND_AXE;
	public static final DeferredItem<Item> NETHER_DIAMOND_SHOVEL;
	public static final DeferredItem<Item> NETHER_DIAMOND_HOE;
	public static final DeferredItem<Item> NETHER_DIAMOND_BLOCK;
	public static final DeferredItem<Item> BATTLE_AXE;
	public static final DeferredItem<Item> WOOD_DAGGER;
	public static final DeferredItem<Item> STONE_DAGGER;
	public static final DeferredItem<Item> IRON_DAGGER;
	public static final DeferredItem<Item> GOLD_DAGGER;
	public static final DeferredItem<Item> DIAMOND_DAGGER;
	public static final DeferredItem<Item> NETHERITE_DAGGER;
	public static final DeferredItem<Item> NETHER_DIAMOND_DAGGER;
	public static final DeferredItem<Item> FLINT_DAGGER;
	public static final DeferredItem<Item> FLINT_SWORD;
	public static final DeferredItem<Item> FLINT_PICKAXE;
	public static final DeferredItem<Item> FLINT_AXE;
	public static final DeferredItem<Item> FLINT_SHOVEL;
	public static final DeferredItem<Item> FLINT_HOE;
	public static final DeferredItem<Item> NETHER_DIAMOND_HELMET;
	public static final DeferredItem<Item> NETHER_DIAMOND_CHESTPLATE;
	public static final DeferredItem<Item> NETHER_DIAMOND_LEGGINGS;
	public static final DeferredItem<Item> NETHER_DIAMOND_BOOTS;
	public static final DeferredItem<Item> SUGAR_BLOCK;
	public static final DeferredItem<Item> SUGAR_BOOTS;
	public static final DeferredItem<Item> RABBIT_BOOTS;
	public static final DeferredItem<Item> PHANTOM_BOOTS;
	public static final DeferredItem<Item> CACTUS_CHESTPLATE;
	public static final DeferredItem<Item> HEARTY_CHESTPLATE;
	public static final DeferredItem<Item> RUBY_ORE;
	public static final DeferredItem<Item> RUBY;
	public static final DeferredItem<Item> RUBY_PICKAXE;
	public static final DeferredItem<Item> RUBY_AXE;
	public static final DeferredItem<Item> RUBY_SWORD;
	public static final DeferredItem<Item> RUBY_SHOVEL;
	public static final DeferredItem<Item> RUBY_HOE;
	public static final DeferredItem<Item> RUBY_BLOCK;
	public static final DeferredItem<Item> RUBY_LEGGINGS;
	public static final DeferredItem<Item> CRYSTAL_LEGGINGS;
	public static final DeferredItem<Item> GOLD_CARROT_HELMET;
	public static final DeferredItem<Item> BLACKSTONE_LEGGINGS;
	public static final DeferredItem<Item> RANDOM_ORE;
	public static final DeferredItem<Item> MIXED_ESSENCE;
	public static final DeferredItem<Item> RUBY_DAGGER;
	public static final DeferredItem<Item> IRON_SUGAR_BOOTS;
	public static final DeferredItem<Item> IRON_RABBIT_BOOTS;
	public static final DeferredItem<Item> IRON_PHANTOM_BOOTS;
	public static final DeferredItem<Item> IRON_CACTUS_CHESTPLATE;
	public static final DeferredItem<Item> IRON_HEARTY_CHESTPLATE;
	public static final DeferredItem<Item> IRON_GOLD_CARROT_HELMET;
	public static final DeferredItem<Item> DIAMOND_SUGAR_BOOTS;
	public static final DeferredItem<Item> DIAMOND_RABBIT_BOOTS;
	public static final DeferredItem<Item> DIAMOND_PHANTOM_BOOTS;
	public static final DeferredItem<Item> DIAMOND_CACTUS_CHESTPLATE;
	public static final DeferredItem<Item> DIAMOND_HEARTY_CHESTPLATE;
	public static final DeferredItem<Item> DIAMOND_RUBY_LEGGINGS;
	public static final DeferredItem<Item> DIAMOND_CRYSTAL_LEGGINGS;
	public static final DeferredItem<Item> DIAMOND_GOLD_CARROT_HELMET;
	public static final DeferredItem<Item> DIAMOND_BLACKSTONE_LEGGINGS;
	public static final DeferredItem<Item> CRYING_OBSIDIAN_HELMET;
	public static final DeferredItem<Item> DIAMOND_CRYING_OBSIDIAN_HELMET;
	public static final DeferredItem<Item> AMOGUS;
	public static final DeferredItem<Item> END_TITANIUM_ORE;
	public static final DeferredItem<Item> END_TITANIUM_SCRAP;
	public static final DeferredItem<Item> END_TITANIUM_INGOT;
	public static final DeferredItem<Item> OBSIDIAN_STICK;
	public static final DeferredItem<Item> END_TITANIUM_SWORD;
	public static final DeferredItem<Item> END_TITANIUM_PICKAXE;
	public static final DeferredItem<Item> END_TITANIUM_AXE;
	public static final DeferredItem<Item> END_TITANIUM_SHOVEL;
	public static final DeferredItem<Item> END_TITANIUM_HOE;
	public static final DeferredItem<Item> END_TITANIUM_HELMET;
	public static final DeferredItem<Item> END_TITANIUM_CHESTPLATE;
	public static final DeferredItem<Item> END_TITANIUM_LEGGINGS;
	public static final DeferredItem<Item> END_TITANIUM_BOOTS;
	public static final DeferredItem<Item> END_TITANIUM_DAGGER;
	public static final DeferredItem<Item> END_TITANIUM_BLOCK;
	public static final DeferredItem<Item> BLUE_SLIMEBALL;
	public static final DeferredItem<Item> BLUE_SLIME_BLOCK;
	public static final DeferredItem<Item> BLUE_MUSHROOM;
	public static final DeferredItem<Item> BLUE_MUSHROOM_BLOCK;
	public static final DeferredItem<Item> GLASS_HELMET;
	public static final DeferredItem<Item> GLASS_CHESTPLATE;
	public static final DeferredItem<Item> GLASS_LEGGINGS;
	public static final DeferredItem<Item> GLASS_BOOTS;
	public static final DeferredItem<Item> PURPLE_MUSHROOM;
	public static final DeferredItem<Item> PURPLE_MUSHROOM_BLOCK;
	public static final DeferredItem<Item> MAGMA_CHESTPLATE;
	public static final DeferredItem<Item> BLACKSTONE_MAGMA;
	public static final DeferredItem<Item> DIAMOND_MAGMA_CHESTPLATE;
	public static final DeferredItem<Item> CHARGED_ICE_ON;
	public static final DeferredItem<Item> CREATIVE_TAB_LOGO;
	public static final DeferredItem<Item> SAPPHIRE;
	public static final DeferredItem<Item> SAPPHIRE_ORE;
	public static final DeferredItem<Item> SAPPHIRE_BLOCK;
	public static final DeferredItem<Item> TOPAZ;
	public static final DeferredItem<Item> TOPAZ_ORE;
	public static final DeferredItem<Item> TOPAZ_BLOCK;
	public static final DeferredItem<Item> SAPPHIRE_SWORD;
	public static final DeferredItem<Item> SAPPHIRE_PICKAXE;
	public static final DeferredItem<Item> SAPPHIRE_AXE;
	public static final DeferredItem<Item> SAPPHIRE_SHOVEL;
	public static final DeferredItem<Item> SAPPHIRE_HOE;
	public static final DeferredItem<Item> SAPPHIRE_DAGGER;
	public static final DeferredItem<Item> SAPPHIRE_HELMET;
	public static final DeferredItem<Item> SAPPHIRE_CHESTPLATE;
	public static final DeferredItem<Item> SAPPHIRE_LEGGINGS;
	public static final DeferredItem<Item> SAPPHIRE_BOOTS;
	public static final DeferredItem<Item> TOPAZ_SWORD;
	public static final DeferredItem<Item> TOPAZ_PICKAXE;
	public static final DeferredItem<Item> TOPAZ_AXE;
	public static final DeferredItem<Item> TOPAZ_SHOVEL;
	public static final DeferredItem<Item> TOPAZ_HOE;
	public static final DeferredItem<Item> TOPAZ_DAGGER;
	public static final DeferredItem<Item> TOPAZ_HELMET;
	public static final DeferredItem<Item> TOPAZ_CHESTPLATE;
	public static final DeferredItem<Item> TOPAZ_LEGGINGS;
	public static final DeferredItem<Item> TOPAZ_BOOTS;
	public static final DeferredItem<Item> FIRE_CRYSTAL;
	public static final DeferredItem<Item> ICE_CRYSTAL;
	public static final DeferredItem<Item> ICE_EFFECT;
	public static final DeferredItem<Item> ELECTRIC_CRYSTAL;
	public static final DeferredItem<Item> FOUR_LEAF_CLOVER;
	public static final DeferredItem<Item> NETHER_DIAMOND_ORE;
	public static final DeferredItem<Item> CRYSTALLITE_BLOCK;
	public static final DeferredItem<Item> CRYSTALLITE_SHARDS;
	public static final DeferredItem<Item> CRYSTALLITE_GEM;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE;
	public static final DeferredItem<Item> CRYSTALLITE_AXE;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL;
	public static final DeferredItem<Item> CRYSTALLITE_HOE;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER;
	public static final DeferredItem<Item> CRYSTALLITE_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_BOOTS;
	public static final DeferredItem<Item> CUT_CRYSTALLITE_BLOCK;
	public static final DeferredItem<Item> TOUGH_CRYSTAL;
	public static final DeferredItem<Item> GILDED_CRYSTAL;
	public static final DeferredItem<Item> MAGIC_CRYSTAL;
	public static final DeferredItem<Item> HEAL_CRYSTAL;
	public static final DeferredItem<Item> DIAMOND_HARD_CRYSTAL;
	public static final DeferredItem<Item> SPIKED_CRYSTAL;
	public static final DeferredItem<Item> SPEEDY_CRYSTAL;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_IRON_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_IRON_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_IRON_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_IRON_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_GOLD_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_GOLD_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_GOLD_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_GOLD_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_LAPIS_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_LAPIS_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_LAPIS_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_LAPIS_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_REDSTONE_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_REDSTONE_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_REDSTONE_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_REDSTONE_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_DIAMOND_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_DIAMOND_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_DIAMOND_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_DIAMOND_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHERITE_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHERITE_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHERITE_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHERITE_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_RUBY_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_RUBY_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_RUBY_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_RUBY_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SAPPHIRE_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SAPPHIRE_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SAPPHIRE_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SAPPHIRE_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_TOPAZ_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_TOPAZ_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_TOPAZ_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_TOPAZ_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHER_DIAMOND_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHER_DIAMOND_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHER_DIAMOND_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_NETHER_DIAMOND_BOOTS;
	public static final DeferredItem<Item> SKY_CRYSTAL;
	public static final DeferredItem<Item> WINGED_BOOTS_BOOTS;
	public static final DeferredItem<Item> GOLDEN_POTATO;
	public static final DeferredItem<Item> DIAMOND_APPLE;
	public static final DeferredItem<Item> EXPERIENCE_POTION;
	public static final DeferredItem<Item> BERRY_PIE;
	public static final DeferredItem<Item> SUGAR_CLUMP;
	public static final DeferredItem<Item> BLUE_SLIME_STICK;
	public static final DeferredItem<Item> DEEPSLATE_RUBY_ORE;
	public static final DeferredItem<Item> DEEPSLATE_RANDOM_ORE;
	public static final DeferredItem<Item> PURPLE_MOOSHROOM_SPAWN_EGG;
	public static final DeferredItem<Item> FLINT_BLOCKWOOD;
	public static final DeferredItem<Item> DARK_POLISHED_COAL_BLOCK;
	public static final DeferredItem<Item> DARK_POLISHED_COAL_SLAB;
	public static final DeferredItem<Item> DARK_POLISHED_COAL_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_COAL_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_COAL_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_COAL_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_IRON_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_IRON_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_IRON_STAIRS;
	public static final DeferredItem<Item> DARK_POLISHED_IRON_BLOCK;
	public static final DeferredItem<Item> DARK_POLISHED_IRON_SLAB;
	public static final DeferredItem<Item> DARK_POLISHED_IRON_STAIRS;
	public static final DeferredItem<Item> DARK_POLISHED_LAPIS_BLOCK;
	public static final DeferredItem<Item> DARK_POLISHED_LAPIS_SLAB;
	public static final DeferredItem<Item> DARK_POLISHED_LAPIS_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_LAPIS_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_LAPIS_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_LAPIS_STAIRS;
	public static final DeferredItem<Item> POLISHED_DIAMOND_BLOCK;
	public static final DeferredItem<Item> POLISHED_DIAMOND_SLAB;
	public static final DeferredItem<Item> POLISHED_DIAMOND_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_EMERALD_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_EMERALD_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_EMERALD_STAIRS;
	public static final DeferredItem<Item> DARK_POLISHED_EMERALD_BLOCK;
	public static final DeferredItem<Item> DARK_POLISHED_EMERALD_SLAB;
	public static final DeferredItem<Item> DARK_POLISHED_EMERALD_STAIRS;
	public static final DeferredItem<Item> POLISHED_REDSTONE_BLOCK;
	public static final DeferredItem<Item> POLISHED_REDSTONE_SLAB;
	public static final DeferredItem<Item> POLISHED_REDSTONE_STAIRS;
	public static final DeferredItem<Item> POLISHED_RUBY_BLOCK;
	public static final DeferredItem<Item> POLISHED_RUBY_SLAB;
	public static final DeferredItem<Item> POLISHED_RUBY_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_COPPER_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_COPPER_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_COPPER_STAIRS;
	public static final DeferredItem<Item> DARK_POLISHED_COPPER_BLOCK;
	public static final DeferredItem<Item> DARK_POLISHED_COPPER_SLAB;
	public static final DeferredItem<Item> DARK_POLISHED_COPPER_STAIRS;
	public static final DeferredItem<Item> POLISHED_TOPAZ_BLOCK;
	public static final DeferredItem<Item> POLISHED_TOPAZ_SLAB;
	public static final DeferredItem<Item> POLISHED_TOPAZ_STAIRS;
	public static final DeferredItem<Item> POLISHED_GOLD_BLOCK;
	public static final DeferredItem<Item> POLISHED_GOLD_SLAB;
	public static final DeferredItem<Item> POLISHED_GOLD_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_GOLD_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_GOLD_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_GOLD_STAIRS;
	public static final DeferredItem<Item> POLISHED_NETHER_DIAMOND_BLOCK;
	public static final DeferredItem<Item> POLISHED_NETHER_DIAMOND_SLAB;
	public static final DeferredItem<Item> POLISHED_NETHER_DIAMOND_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_NETHER_DIAMOND_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_NETHER_DIAMOND_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_NETHER_DIAMOND_STAIRS;
	public static final DeferredItem<Item> POLISHED_AMETHYST_BLOCK;
	public static final DeferredItem<Item> POLISHED_AMETHYST_SLAB;
	public static final DeferredItem<Item> POLISHED_AMETHYST_STAIRS;
	public static final DeferredItem<Item> LIGHT_POLISHED_AMETHYST_BLOCK;
	public static final DeferredItem<Item> LIGHT_POLISHED_AMETHYST_SLAB;
	public static final DeferredItem<Item> LIGHT_POLISHED_AMETHYST_STAIRS;
	public static final DeferredItem<Item> DARK_POLISHED_COAL_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_COAL_TRAPDOOR;
	public static final DeferredItem<Item> DARK_POLISHED_IRON_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_IRON_TRAPDOOR;
	public static final DeferredItem<Item> DARK_POLISHED_LAPIS_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_LAPIS_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_DIAMOND_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_EMERALD_TRAPDOOR;
	public static final DeferredItem<Item> DARK_POLISHED_EMERALD_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_REDSTONE_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_RUBY_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_COPPER_TRAPDOOR;
	public static final DeferredItem<Item> DARK_POLISHED_COPPER_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_TOPAZ_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_GOLD_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_GOLD_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_NETHER_DIAMOND_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR;
	public static final DeferredItem<Item> POLISHED_AMETHYST_TRAPDOOR;
	public static final DeferredItem<Item> LIGHT_POLISHED_AMETHYST_TRAPDOOR;
	public static final DeferredItem<Item> DARK_POLISHED_COAL_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_COAL_WALL;
	public static final DeferredItem<Item> DARK_POLISHED_IRON_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_IRON_WALL;
	public static final DeferredItem<Item> DARK_POLISHED_LAPIS_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_LAPIS_WALL;
	public static final DeferredItem<Item> POLISHED_DIAMOND_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_EMERALD_WALL;
	public static final DeferredItem<Item> DARK_POLISHED_EMERALD_WALL;
	public static final DeferredItem<Item> POLISHED_REDSTONE_WALL;
	public static final DeferredItem<Item> POLISHED_RUBY_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_COPPER_WALL;
	public static final DeferredItem<Item> DARK_POLISHED_COPPER_WALL;
	public static final DeferredItem<Item> POLISHED_TOPAZ_WALL;
	public static final DeferredItem<Item> POLISHED_GOLD_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_GOLD_WALL;
	public static final DeferredItem<Item> POLISHED_NETHER_DIAMOND_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_NETHER_DIAMOND_WALL;
	public static final DeferredItem<Item> POLISHED_AMETHYST_WALL;
	public static final DeferredItem<Item> LIGHT_POLISHED_AMETHYST_WALL;
	public static final DeferredItem<Item> NATURE_CRYSTAL;
	public static final DeferredItem<Item> ECHO_CRYSTAL;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_EMERALD_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_EMERALD_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_EMERALD_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_EMERALD_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SCULK_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SCULK_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SCULK_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SCULK_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_CLUSTER_AIR;
	public static final DeferredItem<Item> IRON_GLASS_ARMOR_HELMET;
	public static final DeferredItem<Item> IRON_GLASS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> IRON_GLASS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> IRON_GLASS_ARMOR_BOOTS;
	public static final DeferredItem<Item> DIAMOND_GLASS_ARMOR_HELMET;
	public static final DeferredItem<Item> DIAMOND_GLASS_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> DIAMOND_GLASS_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> DIAMOND_GLASS_ARMOR_BOOTS;
	public static final DeferredItem<Item> CRYSTALLITE_CHARM_BASE;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SKY_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SKY_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SKY_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_SKY_BOOTS;
	public static final DeferredItem<Item> GUARDIAN_SPIKE;
	public static final DeferredItem<Item> APPLE_JUICE;
	public static final DeferredItem<Item> BERRY_SMOOTHIE;
	public static final DeferredItem<Item> EARTH_CRYSTAL;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_AMETHYST_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_AMETHYST_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_AMETHYST_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_AMETHYST_BOOTS;
	public static final DeferredItem<Item> CLIMBABLE_WALL;
	public static final DeferredItem<Item> GUARDIAN_CRYSTAL;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_PRISMARINE_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_PRISMARINE_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_PRISMARINE_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_PRISMARINE_BOOTS;
	public static final DeferredItem<Item> ELECTRIC_STAFF;
	public static final DeferredItem<Item> ICE_STAFF;
	public static final DeferredItem<Item> FIRE_STAFF;
	public static final DeferredItem<Item> WARDEN_STAFF;
	public static final DeferredItem<Item> GUARDIAN_STAFF;
	public static final DeferredItem<Item> JEWELLERY_TABLE;
	public static final DeferredItem<Item> CRYSTALLITE_SWORD_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_DAGGER_HONEY;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_HONEY_HELMET;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_HONEY_CHESTPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_HONEY_LEGGINGS;
	public static final DeferredItem<Item> CRYSTALLITE_ARMOR_HONEY_BOOTS;
	public static final DeferredItem<Item> HIVE_CRYSTAL;
	public static final DeferredItem<Item> ASCENSION_POTION;
	public static final DeferredItem<Item> DESCENSION_POTION;
	public static final DeferredItem<Item> RECALL_POTION;
	public static final DeferredItem<Item> LOST_SOULS_POTION;
	public static final DeferredItem<Item> ENDER_TITANIUM_UPGRADE_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_UPGRADE_SMITHING_TEMPLATE;
	public static final DeferredItem<Item> CRYSTALLITE_BOW;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_IRON;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_GOLD;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_LAPIS;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_REDSTONE;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_NETHERITE;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_RUBY;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_SAPPHIRE;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_TOPAZ;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_NETHER_DIAMOND;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_EMERALD;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_SCULK;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_SKY;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_AMETHYST;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_PRISMARINE;
	public static final DeferredItem<Item> CRYSTALLITE_BOW_HONEY;
	public static final DeferredItem<Item> BARK;
	public static final DeferredItem<Item> WOODEN_HELMET;
	public static final DeferredItem<Item> WOODEN_CHESTPLATE;
	public static final DeferredItem<Item> WOODEN_LEGGINGS;
	public static final DeferredItem<Item> WOODEN_BOOTS;
	public static final DeferredItem<Item> ENRICHED_BLAZE_POWDER;
	public static final DeferredItem<Item> SUPER_ENRICHED_BLAZE_POWDER;
	public static final DeferredItem<Item> ULTRA_ENRICHED_BLAZE_POWDER;
	public static final DeferredItem<Item> MYSTIC_POTION;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_REDSTONE_UPGRADE_1;
	public static final DeferredItem<Item> CRYSTALLITE_PICKAXE_REDSTONE_UPGRADE_2;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_REDSTONE_UPGRADE_1;
	public static final DeferredItem<Item> CRYSTALLITE_AXE_REDSTONE_UPGRADE_2;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_REDSTONE_UPGRADE_1;
	public static final DeferredItem<Item> CRYSTALLITE_SHOVEL_REDSTONE_UPGRADE_2;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_REDSTONE_UPGRADE_1;
	public static final DeferredItem<Item> CRYSTALLITE_HOE_REDSTONE_UPGRADE_2;
	public static final DeferredItem<Item> AMETHYST_HELMET;
	public static final DeferredItem<Item> DRIPSTONE_BOOTS;
	public static final DeferredItem<Item> HONEYCOMB_HELMET;
	public static final DeferredItem<Item> REDSTONE_SWORD;
	public static final DeferredItem<Item> REDSTONE_DAGGER;
	public static final DeferredItem<Item> LAPIS_SWORD;
	public static final DeferredItem<Item> LAPIS_DAGGER;
	public static final DeferredItem<Item> EMERALD_SWORD;
	public static final DeferredItem<Item> EMERALD_DAGGER;
	public static final DeferredItem<Item> TOUGH_NECKLACE;
	public static final DeferredItem<Item> GILDED_BRACELET;
	public static final DeferredItem<Item> MAGIC_RING;
	public static final DeferredItem<Item> HEART_CHARM;
	public static final DeferredItem<Item> DIAMOND_HARD_PLATE;
	public static final DeferredItem<Item> WITHERED_GAUNTLET;
	public static final DeferredItem<Item> SPEEDY_NECKLACE;
	public static final DeferredItem<Item> ICY_BRACELET;
	public static final DeferredItem<Item> ELECTRIC_NECKLACE;
	public static final DeferredItem<Item> FLAMING_CIRCLET;
	public static final DeferredItem<Item> NATURE_RING;
	public static final DeferredItem<Item> WARDEN_HEADBAND;
	public static final DeferredItem<Item> REFLECT_CHARM;
	public static final DeferredItem<Item> EARTH_CIRCLET;
	public static final DeferredItem<Item> GUARDIAN_NECKLACE;
	public static final DeferredItem<Item> CURING_CHARM;
	public static final DeferredItem<Item> BOUNCY_BRACELET;
	public static final DeferredItem<Item> LUCKY_CHARM;
	public static final DeferredItem<Item> ENDER_GOGGLES;
	public static final DeferredItem<Item> POISON_CHARM;
	public static final DeferredItem<Item> ENERGY_VIAL;
	public static final DeferredItem<Item> EMERALD_ENERGY_VIAL;
	public static final DeferredItem<Item> NETHERITE_ENERGY_VIAL;
	static {
		NETHER_DIAMOND = REGISTRY.register("nether_diamond", NetherDiamondItem::new);
		NETHER_DIAMOND_SWORD = REGISTRY.register("nether_diamond_sword", NetherDiamondSwordItem::new);
		NETHER_DIAMOND_PICKAXE = REGISTRY.register("nether_diamond_pickaxe", NetherDiamondPickaxeItem::new);
		NETHER_DIAMOND_AXE = REGISTRY.register("nether_diamond_axe", NetherDiamondAxeItem::new);
		NETHER_DIAMOND_SHOVEL = REGISTRY.register("nether_diamond_shovel", NetherDiamondShovelItem::new);
		NETHER_DIAMOND_HOE = REGISTRY.register("nether_diamond_hoe", NetherDiamondHoeItem::new);
		NETHER_DIAMOND_BLOCK = block(BetterToolsModBlocks.NETHER_DIAMOND_BLOCK);
		BATTLE_AXE = REGISTRY.register("battle_axe", BattleAxeItem::new);
		WOOD_DAGGER = REGISTRY.register("wood_dagger", WoodDaggerItem::new);
		STONE_DAGGER = REGISTRY.register("stone_dagger", StoneDaggerItem::new);
		IRON_DAGGER = REGISTRY.register("iron_dagger", IronDaggerItem::new);
		GOLD_DAGGER = REGISTRY.register("gold_dagger", GoldDaggerItem::new);
		DIAMOND_DAGGER = REGISTRY.register("diamond_dagger", DiamondDaggerItem::new);
		NETHERITE_DAGGER = REGISTRY.register("netherite_dagger", NetheriteDaggerItem::new);
		NETHER_DIAMOND_DAGGER = REGISTRY.register("nether_diamond_dagger", NetherDiamondDaggerItem::new);
		FLINT_DAGGER = REGISTRY.register("flint_dagger", FlintDaggerItem::new);
		FLINT_SWORD = REGISTRY.register("flint_sword", FlintSwordItem::new);
		FLINT_PICKAXE = REGISTRY.register("flint_pickaxe", FlintPickaxeItem::new);
		FLINT_AXE = REGISTRY.register("flint_axe", FlintAxeItem::new);
		FLINT_SHOVEL = REGISTRY.register("flint_shovel", FlintShovelItem::new);
		FLINT_HOE = REGISTRY.register("flint_hoe", FlintHoeItem::new);
		NETHER_DIAMOND_HELMET = REGISTRY.register("nether_diamond_helmet", NetherDiamondArmorItem.Helmet::new);
		NETHER_DIAMOND_CHESTPLATE = REGISTRY.register("nether_diamond_chestplate", NetherDiamondArmorItem.Chestplate::new);
		NETHER_DIAMOND_LEGGINGS = REGISTRY.register("nether_diamond_leggings", NetherDiamondArmorItem.Leggings::new);
		NETHER_DIAMOND_BOOTS = REGISTRY.register("nether_diamond_boots", NetherDiamondArmorItem.Boots::new);
		SUGAR_BLOCK = block(BetterToolsModBlocks.SUGAR_BLOCK);
		SUGAR_BOOTS = REGISTRY.register("sugar_boots", SugarBootsItem.Boots::new);
		RABBIT_BOOTS = REGISTRY.register("rabbit_boots", RabbitBootsItem.Boots::new);
		PHANTOM_BOOTS = REGISTRY.register("phantom_boots", PhantomBootsItem.Boots::new);
		CACTUS_CHESTPLATE = REGISTRY.register("cactus_chestplate", CactusBodyItem.Chestplate::new);
		HEARTY_CHESTPLATE = REGISTRY.register("hearty_chestplate", HeartyBodyItem.Chestplate::new);
		RUBY_ORE = block(BetterToolsModBlocks.RUBY_ORE);
		RUBY = REGISTRY.register("ruby", RubyItem::new);
		RUBY_PICKAXE = REGISTRY.register("ruby_pickaxe", RubyToolsPickaxeItem::new);
		RUBY_AXE = REGISTRY.register("ruby_axe", RubyToolsAxeItem::new);
		RUBY_SWORD = REGISTRY.register("ruby_sword", RubyToolsSwordItem::new);
		RUBY_SHOVEL = REGISTRY.register("ruby_shovel", RubyToolsShovelItem::new);
		RUBY_HOE = REGISTRY.register("ruby_hoe", RubyToolsHoeItem::new);
		RUBY_BLOCK = block(BetterToolsModBlocks.RUBY_BLOCK);
		RUBY_LEGGINGS = REGISTRY.register("ruby_leggings", RubyArmorItem.Leggings::new);
		CRYSTAL_LEGGINGS = REGISTRY.register("crystal_leggings", CrystalLegsItem.Leggings::new);
		GOLD_CARROT_HELMET = REGISTRY.register("gold_carrot_helmet", GoldCarrotArmorItem.Helmet::new);
		BLACKSTONE_LEGGINGS = REGISTRY.register("blackstone_leggings", BlackstoneLegsItem.Leggings::new);
		RANDOM_ORE = block(BetterToolsModBlocks.RANDOM_ORE);
		MIXED_ESSENCE = REGISTRY.register("mixed_essence", RandomGemItem::new);
		RUBY_DAGGER = REGISTRY.register("ruby_dagger", RubyDaggerItem::new);
		IRON_SUGAR_BOOTS = REGISTRY.register("iron_sugar_boots", IronSugarBootsItem.Boots::new);
		IRON_RABBIT_BOOTS = REGISTRY.register("iron_rabbit_boots", IronRabbitBootsItem.Boots::new);
		IRON_PHANTOM_BOOTS = REGISTRY.register("iron_phantom_boots", IronPhantomBootsItem.Boots::new);
		IRON_CACTUS_CHESTPLATE = REGISTRY.register("iron_cactus_chestplate", IronCactusBodyItem.Chestplate::new);
		IRON_HEARTY_CHESTPLATE = REGISTRY.register("iron_hearty_chestplate", IronHeartyBodyItem.Chestplate::new);
		IRON_GOLD_CARROT_HELMET = REGISTRY.register("iron_gold_carrot_helmet", IronGoldCarrotHatItem.Helmet::new);
		DIAMOND_SUGAR_BOOTS = REGISTRY.register("diamond_sugar_boots", DiamondSugarBootsItem.Boots::new);
		DIAMOND_RABBIT_BOOTS = REGISTRY.register("diamond_rabbit_boots", DiamondRabbitBootsItem.Boots::new);
		DIAMOND_PHANTOM_BOOTS = REGISTRY.register("diamond_phantom_boots", DiamondPhantomBootsItem.Boots::new);
		DIAMOND_CACTUS_CHESTPLATE = REGISTRY.register("diamond_cactus_chestplate", DiamondCactusBodyItem.Chestplate::new);
		DIAMOND_HEARTY_CHESTPLATE = REGISTRY.register("diamond_hearty_chestplate", DiamondHeartyBodyItem.Chestplate::new);
		DIAMOND_RUBY_LEGGINGS = REGISTRY.register("diamond_ruby_leggings", DiamondRubyLegsItem.Leggings::new);
		DIAMOND_CRYSTAL_LEGGINGS = REGISTRY.register("diamond_crystal_leggings", DiamondCrystalLegsItem.Leggings::new);
		DIAMOND_GOLD_CARROT_HELMET = REGISTRY.register("diamond_gold_carrot_helmet", DiamondGoldCarrotHatItem.Helmet::new);
		DIAMOND_BLACKSTONE_LEGGINGS = REGISTRY.register("diamond_blackstone_leggings", DiamondBlackstoneLegsItem.Leggings::new);
		CRYING_OBSIDIAN_HELMET = REGISTRY.register("crying_obsidian_helmet", CryingObsidianHelmetItem.Helmet::new);
		DIAMOND_CRYING_OBSIDIAN_HELMET = REGISTRY.register("diamond_crying_obsidian_helmet", DiamondCryingObsidianHelmetItem.Helmet::new);
		AMOGUS = REGISTRY.register("amogus", AmogusItem::new);
		END_TITANIUM_ORE = block(BetterToolsModBlocks.END_TITANIUM_ORE);
		END_TITANIUM_SCRAP = REGISTRY.register("end_titanium_scrap", EndTitaniumScrapItem::new);
		END_TITANIUM_INGOT = REGISTRY.register("end_titanium_ingot", EndTitaniumIngotItem::new);
		OBSIDIAN_STICK = REGISTRY.register("obsidian_stick", ObsidianStickItem::new);
		END_TITANIUM_SWORD = REGISTRY.register("end_titanium_sword", EndTitaniumSwordItem::new);
		END_TITANIUM_PICKAXE = REGISTRY.register("end_titanium_pickaxe", EndTitaniumPickaxeItem::new);
		END_TITANIUM_AXE = REGISTRY.register("end_titanium_axe", EndTitaniumAxeItem::new);
		END_TITANIUM_SHOVEL = REGISTRY.register("end_titanium_shovel", EndTitaniumShovelItem::new);
		END_TITANIUM_HOE = REGISTRY.register("end_titanium_hoe", EndTitaniumHoeItem::new);
		END_TITANIUM_HELMET = REGISTRY.register("end_titanium_helmet", EndTitaniumArmorItem.Helmet::new);
		END_TITANIUM_CHESTPLATE = REGISTRY.register("end_titanium_chestplate", EndTitaniumArmorItem.Chestplate::new);
		END_TITANIUM_LEGGINGS = REGISTRY.register("end_titanium_leggings", EndTitaniumArmorItem.Leggings::new);
		END_TITANIUM_BOOTS = REGISTRY.register("end_titanium_boots", EndTitaniumArmorItem.Boots::new);
		END_TITANIUM_DAGGER = REGISTRY.register("end_titanium_dagger", EndTitaniumDaggerItem::new);
		END_TITANIUM_BLOCK = block(BetterToolsModBlocks.END_TITANIUM_BLOCK);
		BLUE_SLIMEBALL = REGISTRY.register("blue_slimeball", BlueSlimeballItem::new);
		BLUE_SLIME_BLOCK = block(BetterToolsModBlocks.BLUE_SLIME_BLOCK);
		BLUE_MUSHROOM = block(BetterToolsModBlocks.BLUE_MUSHROOM);
		BLUE_MUSHROOM_BLOCK = block(BetterToolsModBlocks.BLUE_MUSHROOM_BLOCK);
		GLASS_HELMET = REGISTRY.register("glass_helmet", GlassArmorItem.Helmet::new);
		GLASS_CHESTPLATE = REGISTRY.register("glass_chestplate", GlassArmorItem.Chestplate::new);
		GLASS_LEGGINGS = REGISTRY.register("glass_leggings", GlassArmorItem.Leggings::new);
		GLASS_BOOTS = REGISTRY.register("glass_boots", GlassArmorItem.Boots::new);
		PURPLE_MUSHROOM = block(BetterToolsModBlocks.PURPLE_MUSHROOM);
		PURPLE_MUSHROOM_BLOCK = block(BetterToolsModBlocks.PURPLE_MUSHROOM_BLOCK);
		MAGMA_CHESTPLATE = REGISTRY.register("magma_chestplate", MagmaBodyItem.Chestplate::new);
		BLACKSTONE_MAGMA = block(BetterToolsModBlocks.BLACKSTONE_MAGMA);
		DIAMOND_MAGMA_CHESTPLATE = REGISTRY.register("diamond_magma_chestplate", DiamondMagmaBodyItem.Chestplate::new);
		CHARGED_ICE_ON = block(BetterToolsModBlocks.CHARGED_ICE_ON);
		CREATIVE_TAB_LOGO = REGISTRY.register("creative_tab_logo", CreativeTabLogoItem::new);
		SAPPHIRE = REGISTRY.register("sapphire", SapphireItem::new);
		SAPPHIRE_ORE = block(BetterToolsModBlocks.SAPPHIRE_ORE);
		SAPPHIRE_BLOCK = block(BetterToolsModBlocks.SAPPHIRE_BLOCK);
		TOPAZ = REGISTRY.register("topaz", TopazItem::new);
		TOPAZ_ORE = block(BetterToolsModBlocks.TOPAZ_ORE);
		TOPAZ_BLOCK = block(BetterToolsModBlocks.TOPAZ_BLOCK);
		SAPPHIRE_SWORD = REGISTRY.register("sapphire_sword", SapphireSwordItem::new);
		SAPPHIRE_PICKAXE = REGISTRY.register("sapphire_pickaxe", SapphirePickaxeItem::new);
		SAPPHIRE_AXE = REGISTRY.register("sapphire_axe", SapphireAxeItem::new);
		SAPPHIRE_SHOVEL = REGISTRY.register("sapphire_shovel", SapphireShovelItem::new);
		SAPPHIRE_HOE = REGISTRY.register("sapphire_hoe", SapphireHoeItem::new);
		SAPPHIRE_DAGGER = REGISTRY.register("sapphire_dagger", SapphireDaggerItem::new);
		SAPPHIRE_HELMET = REGISTRY.register("sapphire_helmet", SapphireArmorItem.Helmet::new);
		SAPPHIRE_CHESTPLATE = REGISTRY.register("sapphire_chestplate", SapphireArmorItem.Chestplate::new);
		SAPPHIRE_LEGGINGS = REGISTRY.register("sapphire_leggings", SapphireArmorItem.Leggings::new);
		SAPPHIRE_BOOTS = REGISTRY.register("sapphire_boots", SapphireArmorItem.Boots::new);
		TOPAZ_SWORD = REGISTRY.register("topaz_sword", TopazSwordItem::new);
		TOPAZ_PICKAXE = REGISTRY.register("topaz_pickaxe", TopazPickaxeItem::new);
		TOPAZ_AXE = REGISTRY.register("topaz_axe", TopazAxeItem::new);
		TOPAZ_SHOVEL = REGISTRY.register("topaz_shovel", TopazShovelItem::new);
		TOPAZ_HOE = REGISTRY.register("topaz_hoe", TopazHoeItem::new);
		TOPAZ_DAGGER = REGISTRY.register("topaz_dagger", TopazDaggerItem::new);
		TOPAZ_HELMET = REGISTRY.register("topaz_helmet", TopazArmorItem.Helmet::new);
		TOPAZ_CHESTPLATE = REGISTRY.register("topaz_chestplate", TopazArmorItem.Chestplate::new);
		TOPAZ_LEGGINGS = REGISTRY.register("topaz_leggings", TopazArmorItem.Leggings::new);
		TOPAZ_BOOTS = REGISTRY.register("topaz_boots", TopazArmorItem.Boots::new);
		FIRE_CRYSTAL = REGISTRY.register("fire_crystal", FireCoreItem::new);
		ICE_CRYSTAL = REGISTRY.register("ice_crystal", IceCoreItem::new);
		ICE_EFFECT = REGISTRY.register("ice_effect", IceEffectItem::new);
		ELECTRIC_CRYSTAL = REGISTRY.register("electric_crystal", ElectricCoreItem::new);
		FOUR_LEAF_CLOVER = block(BetterToolsModBlocks.FOUR_LEAF_CLOVER);
		NETHER_DIAMOND_ORE = block(BetterToolsModBlocks.NETHER_DIAMOND_ORE);
		CRYSTALLITE_BLOCK = block(BetterToolsModBlocks.CRYSTALLITE_BLOCK, new Item.Properties().fireResistant());
		CRYSTALLITE_SHARDS = REGISTRY.register("crystallite_shards", CrystalliteShardsItem::new);
		CRYSTALLITE_GEM = REGISTRY.register("crystallite_gem", CrystaliteGemItem::new);
		CRYSTALLITE_SWORD = REGISTRY.register("crystallite_sword", CrystalliteSwordItem::new);
		CRYSTALLITE_PICKAXE = REGISTRY.register("crystallite_pickaxe", CrystallitePickaxeItem::new);
		CRYSTALLITE_AXE = REGISTRY.register("crystallite_axe", CrystalliteAxeItem::new);
		CRYSTALLITE_SHOVEL = REGISTRY.register("crystallite_shovel", CrystalliteShovelItem::new);
		CRYSTALLITE_HOE = REGISTRY.register("crystallite_hoe", CrystalliteHoeItem::new);
		CRYSTALLITE_DAGGER = REGISTRY.register("crystallite_dagger", CrystalliteDaggerItem::new);
		CRYSTALLITE_HELMET = REGISTRY.register("crystallite_helmet", CrystalliteArmorItem.Helmet::new);
		CRYSTALLITE_CHESTPLATE = REGISTRY.register("crystallite_chestplate", CrystalliteArmorItem.Chestplate::new);
		CRYSTALLITE_LEGGINGS = REGISTRY.register("crystallite_leggings", CrystalliteArmorItem.Leggings::new);
		CRYSTALLITE_BOOTS = REGISTRY.register("crystallite_boots", CrystalliteArmorItem.Boots::new);
		CUT_CRYSTALLITE_BLOCK = block(BetterToolsModBlocks.CUT_CRYSTALLITE_BLOCK, new Item.Properties().fireResistant());
		TOUGH_CRYSTAL = REGISTRY.register("tough_crystal", ToughCrystalItem::new);
		GILDED_CRYSTAL = REGISTRY.register("gilded_crystal", GildedCrystalItem::new);
		MAGIC_CRYSTAL = REGISTRY.register("magic_crystal", MagicCrystalItem::new);
		HEAL_CRYSTAL = REGISTRY.register("heal_crystal", HealCrystalItem::new);
		DIAMOND_HARD_CRYSTAL = REGISTRY.register("diamond_hard_crystal", DiamondHardCrystalItem::new);
		SPIKED_CRYSTAL = REGISTRY.register("spiked_crystal", SpikedCrystalItem::new);
		SPEEDY_CRYSTAL = REGISTRY.register("speedy_crystal", SpeedyCrystalItem::new);
		CRYSTALLITE_SWORD_IRON = REGISTRY.register("crystallite_sword_iron", CrystalliteSwordIronItem::new);
		CRYSTALLITE_PICKAXE_IRON = REGISTRY.register("crystallite_pickaxe_iron", CrystallitePickaxeIronItem::new);
		CRYSTALLITE_AXE_IRON = REGISTRY.register("crystallite_axe_iron", CrystalliteAxeIronItem::new);
		CRYSTALLITE_SHOVEL_IRON = REGISTRY.register("crystallite_shovel_iron", CrystalliteShovelIronItem::new);
		CRYSTALLITE_HOE_IRON = REGISTRY.register("crystallite_hoe_iron", CrystalliteHoeIronItem::new);
		CRYSTALLITE_DAGGER_IRON = REGISTRY.register("crystallite_dagger_iron", CrystalliteDaggerIronItem::new);
		CRYSTALLITE_ARMOR_IRON_HELMET = REGISTRY.register("crystallite_armor_iron_helmet", CrystalliteArmorIronItem.Helmet::new);
		CRYSTALLITE_ARMOR_IRON_CHESTPLATE = REGISTRY.register("crystallite_armor_iron_chestplate", CrystalliteArmorIronItem.Chestplate::new);
		CRYSTALLITE_ARMOR_IRON_LEGGINGS = REGISTRY.register("crystallite_armor_iron_leggings", CrystalliteArmorIronItem.Leggings::new);
		CRYSTALLITE_ARMOR_IRON_BOOTS = REGISTRY.register("crystallite_armor_iron_boots", CrystalliteArmorIronItem.Boots::new);
		CRYSTALLITE_SWORD_GOLD = REGISTRY.register("crystallite_sword_gold", CrystalliteSwordGoldItem::new);
		CRYSTALLITE_PICKAXE_GOLD = REGISTRY.register("crystallite_pickaxe_gold", CrystallitePickaxeGoldItem::new);
		CRYSTALLITE_AXE_GOLD = REGISTRY.register("crystallite_axe_gold", CrystalliteAxeGoldItem::new);
		CRYSTALLITE_SHOVEL_GOLD = REGISTRY.register("crystallite_shovel_gold", CrystalliteShovelGoldItem::new);
		CRYSTALLITE_HOE_GOLD = REGISTRY.register("crystallite_hoe_gold", CrystalliteHoeGoldItem::new);
		CRYSTALLITE_DAGGER_GOLD = REGISTRY.register("crystallite_dagger_gold", CrystalliteDaggerGoldItem::new);
		CRYSTALLITE_ARMOR_GOLD_HELMET = REGISTRY.register("crystallite_armor_gold_helmet", CrystalliteArmorGoldItem.Helmet::new);
		CRYSTALLITE_ARMOR_GOLD_CHESTPLATE = REGISTRY.register("crystallite_armor_gold_chestplate", CrystalliteArmorGoldItem.Chestplate::new);
		CRYSTALLITE_ARMOR_GOLD_LEGGINGS = REGISTRY.register("crystallite_armor_gold_leggings", CrystalliteArmorGoldItem.Leggings::new);
		CRYSTALLITE_ARMOR_GOLD_BOOTS = REGISTRY.register("crystallite_armor_gold_boots", CrystalliteArmorGoldItem.Boots::new);
		CRYSTALLITE_SWORD_LAPIS = REGISTRY.register("crystallite_sword_lapis", CrystalliteSwordLapisItem::new);
		CRYSTALLITE_PICKAXE_LAPIS = REGISTRY.register("crystallite_pickaxe_lapis", CrystallitePickaxeLapisItem::new);
		CRYSTALLITE_AXE_LAPIS = REGISTRY.register("crystallite_axe_lapis", CrystalliteAxeLapisItem::new);
		CRYSTALLITE_SHOVEL_LAPIS = REGISTRY.register("crystallite_shovel_lapis", CrystalliteShovelLapisItem::new);
		CRYSTALLITE_HOE_LAPIS = REGISTRY.register("crystallite_hoe_lapis", CrystalliteHoeLapisItem::new);
		CRYSTALLITE_DAGGER_LAPIS = REGISTRY.register("crystallite_dagger_lapis", CrystalliteDaggerLapisItem::new);
		CRYSTALLITE_ARMOR_LAPIS_HELMET = REGISTRY.register("crystallite_armor_lapis_helmet", CrystalliteArmorLapisItem.Helmet::new);
		CRYSTALLITE_ARMOR_LAPIS_CHESTPLATE = REGISTRY.register("crystallite_armor_lapis_chestplate", CrystalliteArmorLapisItem.Chestplate::new);
		CRYSTALLITE_ARMOR_LAPIS_LEGGINGS = REGISTRY.register("crystallite_armor_lapis_leggings", CrystalliteArmorLapisItem.Leggings::new);
		CRYSTALLITE_ARMOR_LAPIS_BOOTS = REGISTRY.register("crystallite_armor_lapis_boots", CrystalliteArmorLapisItem.Boots::new);
		CRYSTALLITE_SWORD_REDSTONE = REGISTRY.register("crystallite_sword_redstone", CrystalliteSwordRedstoneItem::new);
		CRYSTALLITE_PICKAXE_REDSTONE = REGISTRY.register("crystallite_pickaxe_redstone", CrystallitePickaxeRedstoneItem::new);
		CRYSTALLITE_AXE_REDSTONE = REGISTRY.register("crystallite_axe_redstone", CrystalliteAxeRedstoneItem::new);
		CRYSTALLITE_SHOVEL_REDSTONE = REGISTRY.register("crystallite_shovel_redstone", CrystalliteShovelRedstoneItem::new);
		CRYSTALLITE_HOE_REDSTONE = REGISTRY.register("crystallite_hoe_redstone", CrystalliteHoeRedstoneItem::new);
		CRYSTALLITE_DAGGER_REDSTONE = REGISTRY.register("crystallite_dagger_redstone", CrystalliteDaggerRedstoneItem::new);
		CRYSTALLITE_ARMOR_REDSTONE_HELMET = REGISTRY.register("crystallite_armor_redstone_helmet", CrystalliteArmorRedstoneItem.Helmet::new);
		CRYSTALLITE_ARMOR_REDSTONE_CHESTPLATE = REGISTRY.register("crystallite_armor_redstone_chestplate", CrystalliteArmorRedstoneItem.Chestplate::new);
		CRYSTALLITE_ARMOR_REDSTONE_LEGGINGS = REGISTRY.register("crystallite_armor_redstone_leggings", CrystalliteArmorRedstoneItem.Leggings::new);
		CRYSTALLITE_ARMOR_REDSTONE_BOOTS = REGISTRY.register("crystallite_armor_redstone_boots", CrystalliteArmorRedstoneItem.Boots::new);
		CRYSTALLITE_SWORD_DIAMOND = REGISTRY.register("crystallite_sword_diamond", CrystalliteSwordDiamondItem::new);
		CRYSTALLITE_PICKAXE_DIAMOND = REGISTRY.register("crystallite_pickaxe_diamond", CrystallitePickaxeDiamondItem::new);
		CRYSTALLITE_AXE_DIAMOND = REGISTRY.register("crystallite_axe_diamond", CrystalliteAxeDiamondItem::new);
		CRYSTALLITE_SHOVEL_DIAMOND = REGISTRY.register("crystallite_shovel_diamond", CrystalliteShovelDiamondItem::new);
		CRYSTALLITE_HOE_DIAMOND = REGISTRY.register("crystallite_hoe_diamond", CrystalliteHoeDiamondItem::new);
		CRYSTALLITE_DAGGER_DIAMOND = REGISTRY.register("crystallite_dagger_diamond", CrystalliteDaggerDiamondItem::new);
		CRYSTALLITE_ARMOR_DIAMOND_HELMET = REGISTRY.register("crystallite_armor_diamond_helmet", CrystalliteArmorDiamondItem.Helmet::new);
		CRYSTALLITE_ARMOR_DIAMOND_CHESTPLATE = REGISTRY.register("crystallite_armor_diamond_chestplate", CrystalliteArmorDiamondItem.Chestplate::new);
		CRYSTALLITE_ARMOR_DIAMOND_LEGGINGS = REGISTRY.register("crystallite_armor_diamond_leggings", CrystalliteArmorDiamondItem.Leggings::new);
		CRYSTALLITE_ARMOR_DIAMOND_BOOTS = REGISTRY.register("crystallite_armor_diamond_boots", CrystalliteArmorDiamondItem.Boots::new);
		CRYSTALLITE_SWORD_NETHERITE = REGISTRY.register("crystallite_sword_netherite", CrystalliteSwordNetheriteItem::new);
		CRYSTALLITE_PICKAXE_NETHERITE = REGISTRY.register("crystallite_pickaxe_netherite", CrystallitePickaxeNetheriteItem::new);
		CRYSTALLITE_AXE_NETHERITE = REGISTRY.register("crystallite_axe_netherite", CrystalliteAxeNetheriteItem::new);
		CRYSTALLITE_SHOVEL_NETHERITE = REGISTRY.register("crystallite_shovel_netherite", CrystalliteShovelNetheriteItem::new);
		CRYSTALLITE_HOE_NETHERITE = REGISTRY.register("crystallite_hoe_netherite", CrystalliteHoeNetheriteItem::new);
		CRYSTALLITE_DAGGER_NETHERITE = REGISTRY.register("crystallite_dagger_netherite", CrystalliteDaggerNetheriteItem::new);
		CRYSTALLITE_ARMOR_NETHERITE_HELMET = REGISTRY.register("crystallite_armor_netherite_helmet", CrystalliteArmorNetheriteItem.Helmet::new);
		CRYSTALLITE_ARMOR_NETHERITE_CHESTPLATE = REGISTRY.register("crystallite_armor_netherite_chestplate", CrystalliteArmorNetheriteItem.Chestplate::new);
		CRYSTALLITE_ARMOR_NETHERITE_LEGGINGS = REGISTRY.register("crystallite_armor_netherite_leggings", CrystalliteArmorNetheriteItem.Leggings::new);
		CRYSTALLITE_ARMOR_NETHERITE_BOOTS = REGISTRY.register("crystallite_armor_netherite_boots", CrystalliteArmorNetheriteItem.Boots::new);
		CRYSTALLITE_SWORD_RUBY = REGISTRY.register("crystallite_sword_ruby", CrystalliteSwordRubyItem::new);
		CRYSTALLITE_PICKAXE_RUBY = REGISTRY.register("crystallite_pickaxe_ruby", CrystallitePickaxeRubyItem::new);
		CRYSTALLITE_AXE_RUBY = REGISTRY.register("crystallite_axe_ruby", CrystalliteAxeRubyItem::new);
		CRYSTALLITE_SHOVEL_RUBY = REGISTRY.register("crystallite_shovel_ruby", CrystalliteShovelRubyItem::new);
		CRYSTALLITE_HOE_RUBY = REGISTRY.register("crystallite_hoe_ruby", CrystalliteHoeRubyItem::new);
		CRYSTALLITE_DAGGER_RUBY = REGISTRY.register("crystallite_dagger_ruby", CrystalliteDaggerRubyItem::new);
		CRYSTALLITE_ARMOR_RUBY_HELMET = REGISTRY.register("crystallite_armor_ruby_helmet", CrystalliteArmorRubyItem.Helmet::new);
		CRYSTALLITE_ARMOR_RUBY_CHESTPLATE = REGISTRY.register("crystallite_armor_ruby_chestplate", CrystalliteArmorRubyItem.Chestplate::new);
		CRYSTALLITE_ARMOR_RUBY_LEGGINGS = REGISTRY.register("crystallite_armor_ruby_leggings", CrystalliteArmorRubyItem.Leggings::new);
		CRYSTALLITE_ARMOR_RUBY_BOOTS = REGISTRY.register("crystallite_armor_ruby_boots", CrystalliteArmorRubyItem.Boots::new);
		CRYSTALLITE_SWORD_SAPPHIRE = REGISTRY.register("crystallite_sword_sapphire", CrystalliteSwordSapphireItem::new);
		CRYSTALLITE_PICKAXE_SAPPHIRE = REGISTRY.register("crystallite_pickaxe_sapphire", CrystallitePickaxeSapphireItem::new);
		CRYSTALLITE_AXE_SAPPHIRE = REGISTRY.register("crystallite_axe_sapphire", CrystalliteAxeSapphireItem::new);
		CRYSTALLITE_SHOVEL_SAPPHIRE = REGISTRY.register("crystallite_shovel_sapphire", CrystalliteShovelSapphireItem::new);
		CRYSTALLITE_HOE_SAPPHIRE = REGISTRY.register("crystallite_hoe_sapphire", CrystalliteHoeSapphireItem::new);
		CRYSTALLITE_DAGGER_SAPPHIRE = REGISTRY.register("crystallite_dagger_sapphire", CrystalliteDaggerSapphireItem::new);
		CRYSTALLITE_ARMOR_SAPPHIRE_HELMET = REGISTRY.register("crystallite_armor_sapphire_helmet", CrystalliteArmorSapphireItem.Helmet::new);
		CRYSTALLITE_ARMOR_SAPPHIRE_CHESTPLATE = REGISTRY.register("crystallite_armor_sapphire_chestplate", CrystalliteArmorSapphireItem.Chestplate::new);
		CRYSTALLITE_ARMOR_SAPPHIRE_LEGGINGS = REGISTRY.register("crystallite_armor_sapphire_leggings", CrystalliteArmorSapphireItem.Leggings::new);
		CRYSTALLITE_ARMOR_SAPPHIRE_BOOTS = REGISTRY.register("crystallite_armor_sapphire_boots", CrystalliteArmorSapphireItem.Boots::new);
		CRYSTALLITE_SWORD_TOPAZ = REGISTRY.register("crystallite_sword_topaz", CrystalliteSwordTopazItem::new);
		CRYSTALLITE_PICKAXE_TOPAZ = REGISTRY.register("crystallite_pickaxe_topaz", CrystallitePickaxeTopazItem::new);
		CRYSTALLITE_AXE_TOPAZ = REGISTRY.register("crystallite_axe_topaz", CrystalliteAxeTopazItem::new);
		CRYSTALLITE_SHOVEL_TOPAZ = REGISTRY.register("crystallite_shovel_topaz", CrystalliteShovelTopazItem::new);
		CRYSTALLITE_HOE_TOPAZ = REGISTRY.register("crystallite_hoe_topaz", CrystalliteHoeTopazItem::new);
		CRYSTALLITE_DAGGER_TOPAZ = REGISTRY.register("crystallite_dagger_topaz", CrystalliteDaggerTopazItem::new);
		CRYSTALLITE_ARMOR_TOPAZ_HELMET = REGISTRY.register("crystallite_armor_topaz_helmet", CrystalliteArmorTopazItem.Helmet::new);
		CRYSTALLITE_ARMOR_TOPAZ_CHESTPLATE = REGISTRY.register("crystallite_armor_topaz_chestplate", CrystalliteArmorTopazItem.Chestplate::new);
		CRYSTALLITE_ARMOR_TOPAZ_LEGGINGS = REGISTRY.register("crystallite_armor_topaz_leggings", CrystalliteArmorTopazItem.Leggings::new);
		CRYSTALLITE_ARMOR_TOPAZ_BOOTS = REGISTRY.register("crystallite_armor_topaz_boots", CrystalliteArmorTopazItem.Boots::new);
		CRYSTALLITE_SWORD_NETHER_DIAMOND = REGISTRY.register("crystallite_sword_nether_diamond", CrystalliteSwordNetherDiamondItem::new);
		CRYSTALLITE_PICKAXE_NETHER_DIAMOND = REGISTRY.register("crystallite_pickaxe_nether_diamond", CrystallitePickaxeNetherDiamondItem::new);
		CRYSTALLITE_AXE_NETHER_DIAMOND = REGISTRY.register("crystallite_axe_nether_diamond", CrystalliteAxeNetherDiamondItem::new);
		CRYSTALLITE_SHOVEL_NETHER_DIAMOND = REGISTRY.register("crystallite_shovel_nether_diamond", CrystalliteShovelNetherDiamondItem::new);
		CRYSTALLITE_HOE_NETHER_DIAMOND = REGISTRY.register("crystallite_hoe_nether_diamond", CrystalliteHoeNetherDiamondItem::new);
		CRYSTALLITE_DAGGER_NETHER_DIAMOND = REGISTRY.register("crystallite_dagger_nether_diamond", CrystalliteDaggerNetherDiamondItem::new);
		CRYSTALLITE_ARMOR_NETHER_DIAMOND_HELMET = REGISTRY.register("crystallite_armor_nether_diamond_helmet", CrystalliteArmorNetherDiamondItem.Helmet::new);
		CRYSTALLITE_ARMOR_NETHER_DIAMOND_CHESTPLATE = REGISTRY.register("crystallite_armor_nether_diamond_chestplate", CrystalliteArmorNetherDiamondItem.Chestplate::new);
		CRYSTALLITE_ARMOR_NETHER_DIAMOND_LEGGINGS = REGISTRY.register("crystallite_armor_nether_diamond_leggings", CrystalliteArmorNetherDiamondItem.Leggings::new);
		CRYSTALLITE_ARMOR_NETHER_DIAMOND_BOOTS = REGISTRY.register("crystallite_armor_nether_diamond_boots", CrystalliteArmorNetherDiamondItem.Boots::new);
		SKY_CRYSTAL = REGISTRY.register("sky_crystal", SkyCrystalItem::new);
		WINGED_BOOTS_BOOTS = REGISTRY.register("winged_boots_boots", WingedBootsItem.Boots::new);
		GOLDEN_POTATO = REGISTRY.register("golden_potato", GoldenPotatoItem::new);
		DIAMOND_APPLE = REGISTRY.register("diamond_apple", DiamondAppleItem::new);
		EXPERIENCE_POTION = REGISTRY.register("experience_potion", ExperiencePotionItem::new);
		BERRY_PIE = REGISTRY.register("berry_pie", BerryPieItem::new);
		SUGAR_CLUMP = REGISTRY.register("sugar_clump", SugarClumpItem::new);
		BLUE_SLIME_STICK = REGISTRY.register("blue_slime_stick", BlueSlimeStickItem::new);
		DEEPSLATE_RUBY_ORE = block(BetterToolsModBlocks.DEEPSLATE_RUBY_ORE);
		DEEPSLATE_RANDOM_ORE = block(BetterToolsModBlocks.DEEPSLATE_RANDOM_ORE);
		PURPLE_MOOSHROOM_SPAWN_EGG = REGISTRY.register("purple_mooshroom_spawn_egg", () -> new DeferredSpawnEggItem(BetterToolsModEntities.PURPLE_MOOSHROOM, -8776990, -6902353, new Item.Properties()));
		FLINT_BLOCKWOOD = block(BetterToolsModBlocks.FLINT_BLOCKWOOD);
		DARK_POLISHED_COAL_BLOCK = block(BetterToolsModBlocks.DARK_POLISHED_COAL_BLOCK);
		DARK_POLISHED_COAL_SLAB = block(BetterToolsModBlocks.DARK_POLISHED_COAL_SLAB);
		DARK_POLISHED_COAL_STAIRS = block(BetterToolsModBlocks.DARK_POLISHED_COAL_STAIRS);
		LIGHT_POLISHED_COAL_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_COAL_BLOCK);
		LIGHT_POLISHED_COAL_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_COAL_SLAB);
		LIGHT_POLISHED_COAL_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_COAL_STAIRS);
		LIGHT_POLISHED_IRON_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_IRON_BLOCK);
		LIGHT_POLISHED_IRON_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_IRON_SLAB);
		LIGHT_POLISHED_IRON_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_IRON_STAIRS);
		DARK_POLISHED_IRON_BLOCK = block(BetterToolsModBlocks.DARK_POLISHED_IRON_BLOCK);
		DARK_POLISHED_IRON_SLAB = block(BetterToolsModBlocks.DARK_POLISHED_IRON_SLAB);
		DARK_POLISHED_IRON_STAIRS = block(BetterToolsModBlocks.DARK_POLISHED_IRON_STAIRS);
		DARK_POLISHED_LAPIS_BLOCK = block(BetterToolsModBlocks.DARK_POLISHED_LAPIS_BLOCK);
		DARK_POLISHED_LAPIS_SLAB = block(BetterToolsModBlocks.DARK_POLISHED_LAPIS_SLAB);
		DARK_POLISHED_LAPIS_STAIRS = block(BetterToolsModBlocks.DARK_POLISHED_LAPIS_STAIRS);
		LIGHT_POLISHED_LAPIS_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_BLOCK);
		LIGHT_POLISHED_LAPIS_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_SLAB);
		LIGHT_POLISHED_LAPIS_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_STAIRS);
		POLISHED_DIAMOND_BLOCK = block(BetterToolsModBlocks.POLISHED_DIAMOND_BLOCK);
		POLISHED_DIAMOND_SLAB = block(BetterToolsModBlocks.POLISHED_DIAMOND_SLAB);
		POLISHED_DIAMOND_STAIRS = block(BetterToolsModBlocks.POLISHED_DIAMOND_STAIRS);
		LIGHT_POLISHED_EMERALD_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_BLOCK);
		LIGHT_POLISHED_EMERALD_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_SLAB);
		LIGHT_POLISHED_EMERALD_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_STAIRS);
		DARK_POLISHED_EMERALD_BLOCK = block(BetterToolsModBlocks.DARK_POLISHED_EMERALD_BLOCK);
		DARK_POLISHED_EMERALD_SLAB = block(BetterToolsModBlocks.DARK_POLISHED_EMERALD_SLAB);
		DARK_POLISHED_EMERALD_STAIRS = block(BetterToolsModBlocks.DARK_POLISHED_EMERALD_STAIRS);
		POLISHED_REDSTONE_BLOCK = block(BetterToolsModBlocks.POLISHED_REDSTONE_BLOCK);
		POLISHED_REDSTONE_SLAB = block(BetterToolsModBlocks.POLISHED_REDSTONE_SLAB);
		POLISHED_REDSTONE_STAIRS = block(BetterToolsModBlocks.POLISHED_REDSTONE_STAIRS);
		POLISHED_RUBY_BLOCK = block(BetterToolsModBlocks.POLISHED_RUBY_BLOCK);
		POLISHED_RUBY_SLAB = block(BetterToolsModBlocks.POLISHED_RUBY_SLAB);
		POLISHED_RUBY_STAIRS = block(BetterToolsModBlocks.POLISHED_RUBY_STAIRS);
		LIGHT_POLISHED_COPPER_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_BLOCK);
		LIGHT_POLISHED_COPPER_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_SLAB);
		LIGHT_POLISHED_COPPER_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_STAIRS);
		DARK_POLISHED_COPPER_BLOCK = block(BetterToolsModBlocks.DARK_POLISHED_COPPER_BLOCK);
		DARK_POLISHED_COPPER_SLAB = block(BetterToolsModBlocks.DARK_POLISHED_COPPER_SLAB);
		DARK_POLISHED_COPPER_STAIRS = block(BetterToolsModBlocks.DARK_POLISHED_COPPER_STAIRS);
		POLISHED_TOPAZ_BLOCK = block(BetterToolsModBlocks.POLISHED_TOPAZ_BLOCK);
		POLISHED_TOPAZ_SLAB = block(BetterToolsModBlocks.POLISHED_TOPAZ_SLAB);
		POLISHED_TOPAZ_STAIRS = block(BetterToolsModBlocks.POLISHED_TOPAZ_STAIRS);
		POLISHED_GOLD_BLOCK = block(BetterToolsModBlocks.POLISHED_GOLD_BLOCK);
		POLISHED_GOLD_SLAB = block(BetterToolsModBlocks.POLISHED_GOLD_SLAB);
		POLISHED_GOLD_STAIRS = block(BetterToolsModBlocks.POLISHED_GOLD_STAIRS);
		LIGHT_POLISHED_GOLD_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_BLOCK);
		LIGHT_POLISHED_GOLD_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_SLAB);
		LIGHT_POLISHED_GOLD_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_STAIRS);
		POLISHED_NETHER_DIAMOND_BLOCK = block(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_BLOCK);
		POLISHED_NETHER_DIAMOND_SLAB = block(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_SLAB);
		POLISHED_NETHER_DIAMOND_STAIRS = block(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_STAIRS);
		LIGHT_POLISHED_NETHER_DIAMOND_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_BLOCK);
		LIGHT_POLISHED_NETHER_DIAMOND_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_SLAB);
		LIGHT_POLISHED_NETHER_DIAMOND_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_STAIRS);
		POLISHED_AMETHYST_BLOCK = block(BetterToolsModBlocks.POLISHED_AMETHYST_BLOCK);
		POLISHED_AMETHYST_SLAB = block(BetterToolsModBlocks.POLISHED_AMETHYST_SLAB);
		POLISHED_AMETHYST_STAIRS = block(BetterToolsModBlocks.POLISHED_AMETHYST_STAIRS);
		LIGHT_POLISHED_AMETHYST_BLOCK = block(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_BLOCK);
		LIGHT_POLISHED_AMETHYST_SLAB = block(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_SLAB);
		LIGHT_POLISHED_AMETHYST_STAIRS = block(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_STAIRS);
		DARK_POLISHED_COAL_TRAPDOOR = block(BetterToolsModBlocks.DARK_POLISHED_COAL_TRAPDOOR);
		LIGHT_POLISHED_COAL_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_COAL_TRAPDOOR);
		DARK_POLISHED_IRON_TRAPDOOR = block(BetterToolsModBlocks.DARK_POLISHED_IRON_TRAPDOOR);
		LIGHT_POLISHED_IRON_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_IRON_TRAPDOOR);
		DARK_POLISHED_LAPIS_TRAPDOOR = block(BetterToolsModBlocks.DARK_POLISHED_LAPIS_TRAPDOOR);
		LIGHT_POLISHED_LAPIS_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_TRAPDOOR);
		POLISHED_DIAMOND_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_DIAMOND_TRAPDOOR);
		LIGHT_POLISHED_EMERALD_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_TRAPDOOR);
		DARK_POLISHED_EMERALD_TRAPDOOR = block(BetterToolsModBlocks.DARK_POLISHED_EMERALD_TRAPDOOR);
		POLISHED_REDSTONE_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_REDSTONE_TRAPDOOR);
		POLISHED_RUBY_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_RUBY_TRAPDOOR);
		LIGHT_POLISHED_COPPER_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_TRAPDOOR);
		DARK_POLISHED_COPPER_TRAPDOOR = block(BetterToolsModBlocks.DARK_POLISHED_COPPER_TRAPDOOR);
		POLISHED_TOPAZ_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_TOPAZ_TRAPDOOR);
		POLISHED_GOLD_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_GOLD_TRAPDOOR);
		LIGHT_POLISHED_GOLD_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_TRAPDOOR);
		POLISHED_NETHER_DIAMOND_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_TRAPDOOR);
		LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR);
		POLISHED_AMETHYST_TRAPDOOR = block(BetterToolsModBlocks.POLISHED_AMETHYST_TRAPDOOR);
		LIGHT_POLISHED_AMETHYST_TRAPDOOR = block(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_TRAPDOOR);
		DARK_POLISHED_COAL_WALL = block(BetterToolsModBlocks.DARK_POLISHED_COAL_WALL);
		LIGHT_POLISHED_COAL_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_COAL_WALL);
		DARK_POLISHED_IRON_WALL = block(BetterToolsModBlocks.DARK_POLISHED_IRON_WALL);
		LIGHT_POLISHED_IRON_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_IRON_WALL);
		DARK_POLISHED_LAPIS_WALL = block(BetterToolsModBlocks.DARK_POLISHED_LAPIS_WALL);
		LIGHT_POLISHED_LAPIS_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_LAPIS_WALL);
		POLISHED_DIAMOND_WALL = block(BetterToolsModBlocks.POLISHED_DIAMOND_WALL);
		LIGHT_POLISHED_EMERALD_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_EMERALD_WALL);
		DARK_POLISHED_EMERALD_WALL = block(BetterToolsModBlocks.DARK_POLISHED_EMERALD_WALL);
		POLISHED_REDSTONE_WALL = block(BetterToolsModBlocks.POLISHED_REDSTONE_WALL);
		POLISHED_RUBY_WALL = block(BetterToolsModBlocks.POLISHED_RUBY_WALL);
		LIGHT_POLISHED_COPPER_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_COPPER_WALL);
		DARK_POLISHED_COPPER_WALL = block(BetterToolsModBlocks.DARK_POLISHED_COPPER_WALL);
		POLISHED_TOPAZ_WALL = block(BetterToolsModBlocks.POLISHED_TOPAZ_WALL);
		POLISHED_GOLD_WALL = block(BetterToolsModBlocks.POLISHED_GOLD_WALL);
		LIGHT_POLISHED_GOLD_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_GOLD_WALL);
		POLISHED_NETHER_DIAMOND_WALL = block(BetterToolsModBlocks.POLISHED_NETHER_DIAMOND_WALL);
		LIGHT_POLISHED_NETHER_DIAMOND_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_NETHER_DIAMOND_WALL);
		POLISHED_AMETHYST_WALL = block(BetterToolsModBlocks.POLISHED_AMETHYST_WALL);
		LIGHT_POLISHED_AMETHYST_WALL = block(BetterToolsModBlocks.LIGHT_POLISHED_AMETHYST_WALL);
		NATURE_CRYSTAL = REGISTRY.register("nature_crystal", NatureCrystalItem::new);
		ECHO_CRYSTAL = REGISTRY.register("echo_crystal", EchoCrystalItem::new);
		CRYSTALLITE_SWORD_EMERALD = REGISTRY.register("crystallite_sword_emerald", CrystalliteSwordEmeraldItem::new);
		CRYSTALLITE_PICKAXE_EMERALD = REGISTRY.register("crystallite_pickaxe_emerald", CrystallitePickaxeEmeraldItem::new);
		CRYSTALLITE_AXE_EMERALD = REGISTRY.register("crystallite_axe_emerald", CrystalliteAxeEmeraldItem::new);
		CRYSTALLITE_SHOVEL_EMERALD = REGISTRY.register("crystallite_shovel_emerald", CrystalliteShovelEmeraldItem::new);
		CRYSTALLITE_HOE_EMERALD = REGISTRY.register("crystallite_hoe_emerald", CrystalliteHoeEmeraldItem::new);
		CRYSTALLITE_DAGGER_EMERALD = REGISTRY.register("crystallite_dagger_emerald", CrystalliteDaggerEmeraldItem::new);
		CRYSTALLITE_ARMOR_EMERALD_HELMET = REGISTRY.register("crystallite_armor_emerald_helmet", CrystalliteArmorEmeraldItem.Helmet::new);
		CRYSTALLITE_ARMOR_EMERALD_CHESTPLATE = REGISTRY.register("crystallite_armor_emerald_chestplate", CrystalliteArmorEmeraldItem.Chestplate::new);
		CRYSTALLITE_ARMOR_EMERALD_LEGGINGS = REGISTRY.register("crystallite_armor_emerald_leggings", CrystalliteArmorEmeraldItem.Leggings::new);
		CRYSTALLITE_ARMOR_EMERALD_BOOTS = REGISTRY.register("crystallite_armor_emerald_boots", CrystalliteArmorEmeraldItem.Boots::new);
		CRYSTALLITE_SWORD_SCULK = REGISTRY.register("crystallite_sword_sculk", CrystalliteSwordSculkItem::new);
		CRYSTALLITE_PICKAXE_SCULK = REGISTRY.register("crystallite_pickaxe_sculk", CrystallitePickaxeSculkItem::new);
		CRYSTALLITE_AXE_SCULK = REGISTRY.register("crystallite_axe_sculk", CrystalliteAxeSculkItem::new);
		CRYSTALLITE_SHOVEL_SCULK = REGISTRY.register("crystallite_shovel_sculk", CrystalliteShovelSculkItem::new);
		CRYSTALLITE_HOE_SCULK = REGISTRY.register("crystallite_hoe_sculk", CrystalliteHoeSculkItem::new);
		CRYSTALLITE_DAGGER_SCULK = REGISTRY.register("crystallite_dagger_sculk", CrystalliteDaggerSculkItem::new);
		CRYSTALLITE_ARMOR_SCULK_HELMET = REGISTRY.register("crystallite_armor_sculk_helmet", CrystalliteArmorSculkItem.Helmet::new);
		CRYSTALLITE_ARMOR_SCULK_CHESTPLATE = REGISTRY.register("crystallite_armor_sculk_chestplate", CrystalliteArmorSculkItem.Chestplate::new);
		CRYSTALLITE_ARMOR_SCULK_LEGGINGS = REGISTRY.register("crystallite_armor_sculk_leggings", CrystalliteArmorSculkItem.Leggings::new);
		CRYSTALLITE_ARMOR_SCULK_BOOTS = REGISTRY.register("crystallite_armor_sculk_boots", CrystalliteArmorSculkItem.Boots::new);
		CRYSTALLITE_CLUSTER_AIR = block(BetterToolsModBlocks.CRYSTALLITE_CLUSTER_AIR);
		IRON_GLASS_ARMOR_HELMET = REGISTRY.register("iron_glass_armor_helmet", IronGlassArmorItem.Helmet::new);
		IRON_GLASS_ARMOR_CHESTPLATE = REGISTRY.register("iron_glass_armor_chestplate", IronGlassArmorItem.Chestplate::new);
		IRON_GLASS_ARMOR_LEGGINGS = REGISTRY.register("iron_glass_armor_leggings", IronGlassArmorItem.Leggings::new);
		IRON_GLASS_ARMOR_BOOTS = REGISTRY.register("iron_glass_armor_boots", IronGlassArmorItem.Boots::new);
		DIAMOND_GLASS_ARMOR_HELMET = REGISTRY.register("diamond_glass_armor_helmet", DiamondGlassArmorItem.Helmet::new);
		DIAMOND_GLASS_ARMOR_CHESTPLATE = REGISTRY.register("diamond_glass_armor_chestplate", DiamondGlassArmorItem.Chestplate::new);
		DIAMOND_GLASS_ARMOR_LEGGINGS = REGISTRY.register("diamond_glass_armor_leggings", DiamondGlassArmorItem.Leggings::new);
		DIAMOND_GLASS_ARMOR_BOOTS = REGISTRY.register("diamond_glass_armor_boots", DiamondGlassArmorItem.Boots::new);
		CRYSTALLITE_CHARM_BASE = REGISTRY.register("crystallite_charm_base", CrystalliteCharmBaseItem::new);
		CRYSTALLITE_SWORD_SKY = REGISTRY.register("crystallite_sword_sky", CrystalliteSwordSkyItem::new);
		CRYSTALLITE_PICKAXE_SKY = REGISTRY.register("crystallite_pickaxe_sky", CrystallitePickaxeSkyItem::new);
		CRYSTALLITE_AXE_SKY = REGISTRY.register("crystallite_axe_sky", CrystalliteAxeSkyItem::new);
		CRYSTALLITE_SHOVEL_SKY = REGISTRY.register("crystallite_shovel_sky", CrystalliteShovelSkyItem::new);
		CRYSTALLITE_HOE_SKY = REGISTRY.register("crystallite_hoe_sky", CrystalliteHoeSkyItem::new);
		CRYSTALLITE_DAGGER_SKY = REGISTRY.register("crystallite_dagger_sky", CrystalliteDaggerSkyItem::new);
		CRYSTALLITE_ARMOR_SKY_HELMET = REGISTRY.register("crystallite_armor_sky_helmet", CrystalliteArmorSkyItem.Helmet::new);
		CRYSTALLITE_ARMOR_SKY_CHESTPLATE = REGISTRY.register("crystallite_armor_sky_chestplate", CrystalliteArmorSkyItem.Chestplate::new);
		CRYSTALLITE_ARMOR_SKY_LEGGINGS = REGISTRY.register("crystallite_armor_sky_leggings", CrystalliteArmorSkyItem.Leggings::new);
		CRYSTALLITE_ARMOR_SKY_BOOTS = REGISTRY.register("crystallite_armor_sky_boots", CrystalliteArmorSkyItem.Boots::new);
		GUARDIAN_SPIKE = REGISTRY.register("guardian_spike", GuardianSpikeItem::new);
		APPLE_JUICE = REGISTRY.register("apple_juice", AppleJuiceItem::new);
		BERRY_SMOOTHIE = REGISTRY.register("berry_smoothie", BerrySmoothieItem::new);
		EARTH_CRYSTAL = REGISTRY.register("earth_crystal", EarthCrystalItem::new);
		CRYSTALLITE_SWORD_AMETHYST = REGISTRY.register("crystallite_sword_amethyst", CrystalliteSwordAmethystItem::new);
		CRYSTALLITE_PICKAXE_AMETHYST = REGISTRY.register("crystallite_pickaxe_amethyst", CrystallitePickaxeAmethystItem::new);
		CRYSTALLITE_AXE_AMETHYST = REGISTRY.register("crystallite_axe_amethyst", CrystalliteAxeAmethystItem::new);
		CRYSTALLITE_SHOVEL_AMETHYST = REGISTRY.register("crystallite_shovel_amethyst", CrystalliteShovelAmethystItem::new);
		CRYSTALLITE_HOE_AMETHYST = REGISTRY.register("crystallite_hoe_amethyst", CrystalliteHoeAmethystItem::new);
		CRYSTALLITE_DAGGER_AMETHYST = REGISTRY.register("crystallite_dagger_amethyst", CrystalliteDaggerAmethystItem::new);
		CRYSTALLITE_ARMOR_AMETHYST_HELMET = REGISTRY.register("crystallite_armor_amethyst_helmet", CrystalliteArmorAmethystItem.Helmet::new);
		CRYSTALLITE_ARMOR_AMETHYST_CHESTPLATE = REGISTRY.register("crystallite_armor_amethyst_chestplate", CrystalliteArmorAmethystItem.Chestplate::new);
		CRYSTALLITE_ARMOR_AMETHYST_LEGGINGS = REGISTRY.register("crystallite_armor_amethyst_leggings", CrystalliteArmorAmethystItem.Leggings::new);
		CRYSTALLITE_ARMOR_AMETHYST_BOOTS = REGISTRY.register("crystallite_armor_amethyst_boots", CrystalliteArmorAmethystItem.Boots::new);
		CLIMBABLE_WALL = block(BetterToolsModBlocks.CLIMBABLE_WALL);
		GUARDIAN_CRYSTAL = REGISTRY.register("guardian_crystal", GuardianCrystalItem::new);
		CRYSTALLITE_SWORD_PRISMARINE = REGISTRY.register("crystallite_sword_prismarine", CrystalliteSwordPrismarineItem::new);
		CRYSTALLITE_PICKAXE_PRISMARINE = REGISTRY.register("crystallite_pickaxe_prismarine", CrystallitePickaxePrismarineItem::new);
		CRYSTALLITE_AXE_PRISMARINE = REGISTRY.register("crystallite_axe_prismarine", CrystalliteAxePrismarineItem::new);
		CRYSTALLITE_SHOVEL_PRISMARINE = REGISTRY.register("crystallite_shovel_prismarine", CrystalliteShovelPrismarineItem::new);
		CRYSTALLITE_HOE_PRISMARINE = REGISTRY.register("crystallite_hoe_prismarine", CrystalliteHoePrismarineItem::new);
		CRYSTALLITE_DAGGER_PRISMARINE = REGISTRY.register("crystallite_dagger_prismarine", CrystalliteDaggerPrismarineItem::new);
		CRYSTALLITE_ARMOR_PRISMARINE_HELMET = REGISTRY.register("crystallite_armor_prismarine_helmet", CrystalliteArmorPrismarineItem.Helmet::new);
		CRYSTALLITE_ARMOR_PRISMARINE_CHESTPLATE = REGISTRY.register("crystallite_armor_prismarine_chestplate", CrystalliteArmorPrismarineItem.Chestplate::new);
		CRYSTALLITE_ARMOR_PRISMARINE_LEGGINGS = REGISTRY.register("crystallite_armor_prismarine_leggings", CrystalliteArmorPrismarineItem.Leggings::new);
		CRYSTALLITE_ARMOR_PRISMARINE_BOOTS = REGISTRY.register("crystallite_armor_prismarine_boots", CrystalliteArmorPrismarineItem.Boots::new);
		ELECTRIC_STAFF = REGISTRY.register("electric_staff", ElectricStaffItem::new);
		ICE_STAFF = REGISTRY.register("ice_staff", IceStaffItem::new);
		FIRE_STAFF = REGISTRY.register("fire_staff", FireStaffItem::new);
		WARDEN_STAFF = REGISTRY.register("warden_staff", WardenStaffItem::new);
		GUARDIAN_STAFF = REGISTRY.register("guardian_staff", GuardianStaffItem::new);
		JEWELLERY_TABLE = block(BetterToolsModBlocks.JEWELLERY_TABLE);
		CRYSTALLITE_SWORD_HONEY = REGISTRY.register("crystallite_sword_honey", CrystalliteSwordHoneyItem::new);
		CRYSTALLITE_PICKAXE_HONEY = REGISTRY.register("crystallite_pickaxe_honey", CrystallitePickaxeHoneyItem::new);
		CRYSTALLITE_AXE_HONEY = REGISTRY.register("crystallite_axe_honey", CrystalliteAxeHoneyItem::new);
		CRYSTALLITE_SHOVEL_HONEY = REGISTRY.register("crystallite_shovel_honey", CrystalliteShovelHoneyItem::new);
		CRYSTALLITE_HOE_HONEY = REGISTRY.register("crystallite_hoe_honey", CrystalliteHoeHoneyItem::new);
		CRYSTALLITE_DAGGER_HONEY = REGISTRY.register("crystallite_dagger_honey", CrystalliteDaggerHoneyItem::new);
		CRYSTALLITE_ARMOR_HONEY_HELMET = REGISTRY.register("crystallite_armor_honey_helmet", CrystalliteArmorHoneyItem.Helmet::new);
		CRYSTALLITE_ARMOR_HONEY_CHESTPLATE = REGISTRY.register("crystallite_armor_honey_chestplate", CrystalliteArmorHoneyItem.Chestplate::new);
		CRYSTALLITE_ARMOR_HONEY_LEGGINGS = REGISTRY.register("crystallite_armor_honey_leggings", CrystalliteArmorHoneyItem.Leggings::new);
		CRYSTALLITE_ARMOR_HONEY_BOOTS = REGISTRY.register("crystallite_armor_honey_boots", CrystalliteArmorHoneyItem.Boots::new);
		HIVE_CRYSTAL = REGISTRY.register("hive_crystal", HiveCrystalItem::new);
		ASCENSION_POTION = REGISTRY.register("ascension_potion", AscensionPotionItem::new);
		DESCENSION_POTION = REGISTRY.register("descension_potion", DescensionPotionItem::new);
		RECALL_POTION = REGISTRY.register("recall_potion", RecallPotionItem::new);
		LOST_SOULS_POTION = REGISTRY.register("lost_souls_potion", LostSoulsPotionItem::new);
		ENDER_TITANIUM_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("ender_titanium_upgrade_smithing_template", EnderTitaniumUpgradeSmithingTemplateItem::new);
		CRYSTALLITE_UPGRADE_SMITHING_TEMPLATE = REGISTRY.register("crystallite_upgrade_smithing_template", CrystalliteUpgradeSmithingTemplateItem::new);
		CRYSTALLITE_BOW = REGISTRY.register("crystallite_bow", CrystalliteBowItem::new);
		CRYSTALLITE_BOW_IRON = REGISTRY.register("crystallite_bow_iron", CrystalliteBowIronItem::new);
		CRYSTALLITE_BOW_GOLD = REGISTRY.register("crystallite_bow_gold", CrystalliteBowGoldItem::new);
		CRYSTALLITE_BOW_LAPIS = REGISTRY.register("crystallite_bow_lapis", CrystalliteBowLapisItem::new);
		CRYSTALLITE_BOW_REDSTONE = REGISTRY.register("crystallite_bow_redstone", CrystalliteBowRedstoneItem::new);
		CRYSTALLITE_BOW_DIAMOND = REGISTRY.register("crystallite_bow_diamond", CrystalliteBowDiamondItem::new);
		CRYSTALLITE_BOW_NETHERITE = REGISTRY.register("crystallite_bow_netherite", CrystalliteBowNetheriteItem::new);
		CRYSTALLITE_BOW_RUBY = REGISTRY.register("crystallite_bow_ruby", CrystalliteBowRubyItem::new);
		CRYSTALLITE_BOW_SAPPHIRE = REGISTRY.register("crystallite_bow_sapphire", CrystalliteBowSapphireItem::new);
		CRYSTALLITE_BOW_TOPAZ = REGISTRY.register("crystallite_bow_topaz", CrystalliteBowTopazItem::new);
		CRYSTALLITE_BOW_NETHER_DIAMOND = REGISTRY.register("crystallite_bow_nether_diamond", CrystalliteBowNetherDiamondItem::new);
		CRYSTALLITE_BOW_EMERALD = REGISTRY.register("crystallite_bow_emerald", CrystalliteBowEmeraldItem::new);
		CRYSTALLITE_BOW_SCULK = REGISTRY.register("crystallite_bow_sculk", CrystalliteBowSculkItem::new);
		CRYSTALLITE_BOW_SKY = REGISTRY.register("crystallite_bow_sky", CrystalliteBowSkyItem::new);
		CRYSTALLITE_BOW_AMETHYST = REGISTRY.register("crystallite_bow_amethyst", CrystalliteBowAmethystItem::new);
		CRYSTALLITE_BOW_PRISMARINE = REGISTRY.register("crystallite_bow_prismarine", CrystalliteBowPrismarineItem::new);
		CRYSTALLITE_BOW_HONEY = REGISTRY.register("crystallite_bow_honey", CrystalliteBowHoneyItem::new);
		BARK = REGISTRY.register("bark", BarkItem::new);
		WOODEN_HELMET = REGISTRY.register("wooden_helmet", WoodenArmorItem.Helmet::new);
		WOODEN_CHESTPLATE = REGISTRY.register("wooden_chestplate", WoodenArmorItem.Chestplate::new);
		WOODEN_LEGGINGS = REGISTRY.register("wooden_leggings", WoodenArmorItem.Leggings::new);
		WOODEN_BOOTS = REGISTRY.register("wooden_boots", WoodenArmorItem.Boots::new);
		ENRICHED_BLAZE_POWDER = REGISTRY.register("enriched_blaze_powder", EnrichedBlazePowderItem::new);
		SUPER_ENRICHED_BLAZE_POWDER = REGISTRY.register("super_enriched_blaze_powder", SuperEnrichedBlazePowderItem::new);
		ULTRA_ENRICHED_BLAZE_POWDER = REGISTRY.register("ultra_enriched_blaze_powder", UltraEnrichedBlazePowderItem::new);
		MYSTIC_POTION = REGISTRY.register("mystic_potion", MysticPotionItem::new);
		CRYSTALLITE_PICKAXE_REDSTONE_UPGRADE_1 = REGISTRY.register("crystallite_pickaxe_redstone_upgrade_1", CrystallitePickaxeRedstoneUpgrade1Item::new);
		CRYSTALLITE_PICKAXE_REDSTONE_UPGRADE_2 = REGISTRY.register("crystallite_pickaxe_redstone_upgrade_2", CrystallitePickaxeRedstoneUpgrade2Item::new);
		CRYSTALLITE_AXE_REDSTONE_UPGRADE_1 = REGISTRY.register("crystallite_axe_redstone_upgrade_1", CrystalliteAxeRedstoneUpgrade1Item::new);
		CRYSTALLITE_AXE_REDSTONE_UPGRADE_2 = REGISTRY.register("crystallite_axe_redstone_upgrade_2", CrystalliteAxeRedstoneUpgrade2Item::new);
		CRYSTALLITE_SHOVEL_REDSTONE_UPGRADE_1 = REGISTRY.register("crystallite_shovel_redstone_upgrade_1", CrystalliteShovelRedstoneUpgrade1Item::new);
		CRYSTALLITE_SHOVEL_REDSTONE_UPGRADE_2 = REGISTRY.register("crystallite_shovel_redstone_upgrade_2", CrystalliteShovelRedstoneUpgrade2Item::new);
		CRYSTALLITE_HOE_REDSTONE_UPGRADE_1 = REGISTRY.register("crystallite_hoe_redstone_upgrade_1", CrystalliteHoeRedstoneUpgrade1Item::new);
		CRYSTALLITE_HOE_REDSTONE_UPGRADE_2 = REGISTRY.register("crystallite_hoe_redstone_upgrade_2", CrystalliteHoeRedstoneUpgrade2Item::new);
		AMETHYST_HELMET = REGISTRY.register("amethyst_helmet", AmethystHelmetItem.Helmet::new);
		DRIPSTONE_BOOTS = REGISTRY.register("dripstone_boots", DripstoneBootsItem.Boots::new);
		HONEYCOMB_HELMET = REGISTRY.register("honeycomb_helmet", HoneycombHelmetItem.Helmet::new);
		REDSTONE_SWORD = REGISTRY.register("redstone_sword", RedstoneSwordItem::new);
		REDSTONE_DAGGER = REGISTRY.register("redstone_dagger", RedstoneDaggerItem::new);
		LAPIS_SWORD = REGISTRY.register("lapis_sword", LapisSwordItem::new);
		LAPIS_DAGGER = REGISTRY.register("lapis_dagger", LapisDaggerItem::new);
		EMERALD_SWORD = REGISTRY.register("emerald_sword", EmeraldSwordItem::new);
		EMERALD_DAGGER = REGISTRY.register("emerald_dagger", EmeraldDaggerItem::new);
		TOUGH_NECKLACE = REGISTRY.register("tough_necklace", ToughNecklaceItem::new);
		GILDED_BRACELET = REGISTRY.register("gilded_bracelet", GildedBraceletItem::new);
		MAGIC_RING = REGISTRY.register("magic_ring", MagicRingItem::new);
		HEART_CHARM = REGISTRY.register("heart_charm", HeartCharmItem::new);
		DIAMOND_HARD_PLATE = REGISTRY.register("diamond_hard_plate", DiamondHardPlateItem::new);
		WITHERED_GAUNTLET = REGISTRY.register("withered_gauntlet", WitheredGauntletItem::new);
		SPEEDY_NECKLACE = REGISTRY.register("speedy_necklace", SpeedyNecklaceItem::new);
		ICY_BRACELET = REGISTRY.register("icy_bracelet", IcyBraceletItem::new);
		ELECTRIC_NECKLACE = REGISTRY.register("electric_necklace", ElectricNecklaceItem::new);
		FLAMING_CIRCLET = REGISTRY.register("flaming_circlet", FlamingCircletItem::new);
		NATURE_RING = REGISTRY.register("nature_ring", NatureRingItem::new);
		WARDEN_HEADBAND = REGISTRY.register("warden_headband", WardenHeadbandItem::new);
		REFLECT_CHARM = REGISTRY.register("reflect_charm", ReflectCharmItem::new);
		EARTH_CIRCLET = REGISTRY.register("earth_circlet", EarthCircletItem::new);
		GUARDIAN_NECKLACE = REGISTRY.register("guardian_necklace", GuardianNecklaceItem::new);
		CURING_CHARM = REGISTRY.register("curing_charm", CuringCharmItem::new);
		BOUNCY_BRACELET = REGISTRY.register("bouncy_bracelet", BouncyBraceletItem::new);
		LUCKY_CHARM = REGISTRY.register("lucky_charm", LuckyCharmItem::new);
		ENDER_GOGGLES = REGISTRY.register("ender_goggles", EnderGogglesItem::new);
		POISON_CHARM = REGISTRY.register("poison_charm", PoisonCharmItem::new);
		ENERGY_VIAL = REGISTRY.register("energy_vial", EnergyVialItem::new);
		EMERALD_ENERGY_VIAL = REGISTRY.register("emerald_energy_vial", EmeraldEnergyVialItem::new);
		NETHERITE_ENERGY_VIAL = REGISTRY.register("netherite_energy_vial", NetheriteEnergyVialItem::new);
	}
	// Start of user code block custom items
	public static final DeferredItem<Item> BLACK_METAL_SIGN = REGISTRY.register("black_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.BLACK_METAL_SIGN.get(), BetterToolsModBlocks.BLACK_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> BLACK_METAL_HANGING_SIGN = REGISTRY.register("black_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.BLACK_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.BLACK_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> BLUE_METAL_SIGN = REGISTRY.register("blue_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.BLUE_METAL_SIGN.get(), BetterToolsModBlocks.BLUE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> BLUE_METAL_HANGING_SIGN = REGISTRY.register("blue_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.BLUE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.BLUE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> BROWN_METAL_SIGN = REGISTRY.register("brown_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.BROWN_METAL_SIGN.get(), BetterToolsModBlocks.BROWN_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> BROWN_METAL_HANGING_SIGN = REGISTRY.register("brown_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.BROWN_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.BROWN_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> CREAM_METAL_SIGN = REGISTRY.register("cream_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.CREAM_METAL_SIGN.get(), BetterToolsModBlocks.CREAM_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> CREAM_METAL_HANGING_SIGN = REGISTRY.register("cream_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.CREAM_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.CREAM_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> CYAN_METAL_SIGN = REGISTRY.register("cyan_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.CYAN_METAL_SIGN.get(), BetterToolsModBlocks.CYAN_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> CYAN_METAL_HANGING_SIGN = REGISTRY.register("cyan_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.CYAN_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.CYAN_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> DARK_ORANGE_METAL_SIGN = REGISTRY.register("dark_orange_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.DARK_ORANGE_METAL_SIGN.get(), BetterToolsModBlocks.DARK_ORANGE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> DARK_ORANGE_METAL_HANGING_SIGN = REGISTRY.register("dark_orange_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.DARK_ORANGE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.DARK_ORANGE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> DARK_PINK_METAL_SIGN = REGISTRY.register("dark_pink_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.DARK_PINK_METAL_SIGN.get(), BetterToolsModBlocks.DARK_PINK_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> DARK_PINK_METAL_HANGING_SIGN = REGISTRY.register("dark_pink_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.DARK_PINK_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.DARK_PINK_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> DARK_RED_METAL_SIGN = REGISTRY.register("dark_red_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.DARK_RED_METAL_SIGN.get(), BetterToolsModBlocks.DARK_RED_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> DARK_RED_METAL_HANGING_SIGN = REGISTRY.register("dark_red_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.DARK_RED_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.DARK_RED_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> GRAY_METAL_SIGN = REGISTRY.register("gray_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.GRAY_METAL_SIGN.get(), BetterToolsModBlocks.GRAY_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> GRAY_METAL_HANGING_SIGN = REGISTRY.register("gray_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.GRAY_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.GRAY_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> GREEN_METAL_SIGN = REGISTRY.register("green_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.GREEN_METAL_SIGN.get(), BetterToolsModBlocks.GREEN_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> GREEN_METAL_HANGING_SIGN = REGISTRY.register("green_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.GREEN_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.GREEN_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> LIGHT_BLUE_METAL_SIGN = REGISTRY.register("light_blue_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.LIGHT_BLUE_METAL_SIGN.get(), BetterToolsModBlocks.LIGHT_BLUE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> LIGHT_BLUE_METAL_HANGING_SIGN = REGISTRY.register("light_blue_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.LIGHT_BLUE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.LIGHT_BLUE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> LIGHT_GRAY_METAL_SIGN = REGISTRY.register("light_gray_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.LIGHT_GRAY_METAL_SIGN.get(), BetterToolsModBlocks.LIGHT_GRAY_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> LIGHT_GRAY_METAL_HANGING_SIGN = REGISTRY.register("light_gray_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.LIGHT_GRAY_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.LIGHT_GRAY_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> LIME_METAL_SIGN = REGISTRY.register("lime_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.LIME_METAL_SIGN.get(), BetterToolsModBlocks.LIME_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> LIME_METAL_HANGING_SIGN = REGISTRY.register("lime_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.LIME_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.LIME_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> MAGENTA_METAL_SIGN = REGISTRY.register("magenta_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.MAGENTA_METAL_SIGN.get(), BetterToolsModBlocks.MAGENTA_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> MAGENTA_METAL_HANGING_SIGN = REGISTRY.register("magenta_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.MAGENTA_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.MAGENTA_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> ORANGE_METAL_SIGN = REGISTRY.register("orange_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.ORANGE_METAL_SIGN.get(), BetterToolsModBlocks.ORANGE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> ORANGE_METAL_HANGING_SIGN = REGISTRY.register("orange_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.ORANGE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.ORANGE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> PINK_METAL_SIGN = REGISTRY.register("pink_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.PINK_METAL_SIGN.get(), BetterToolsModBlocks.PINK_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> PINK_METAL_HANGING_SIGN = REGISTRY.register("pink_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.PINK_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.PINK_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> PURPLE_METAL_SIGN = REGISTRY.register("purple_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.PURPLE_METAL_SIGN.get(), BetterToolsModBlocks.PURPLE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> PURPLE_METAL_HANGING_SIGN = REGISTRY.register("purple_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.PURPLE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.PURPLE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> RED_METAL_SIGN = REGISTRY.register("red_metal_sign", () -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.RED_METAL_SIGN.get(), BetterToolsModBlocks.RED_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> RED_METAL_HANGING_SIGN = REGISTRY.register("red_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.RED_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.RED_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> WHITE_METAL_SIGN = REGISTRY.register("white_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.WHITE_METAL_SIGN.get(), BetterToolsModBlocks.WHITE_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> WHITE_METAL_HANGING_SIGN = REGISTRY.register("white_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.WHITE_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.WHITE_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));
	public static final DeferredItem<Item> YELLOW_METAL_SIGN = REGISTRY.register("yellow_metal_sign",
			() -> new SignItem(new Item.Properties().stacksTo(16), BetterToolsModBlocks.YELLOW_METAL_SIGN.get(), BetterToolsModBlocks.YELLOW_METAL_WALL_SIGN.get()));
	public static final DeferredItem<Item> YELLOW_METAL_HANGING_SIGN = REGISTRY.register("yellow_metal_hanging_sign",
			() -> new HangingSignItem(BetterToolsModBlocks.YELLOW_METAL_HANGING_SIGN.get(), BetterToolsModBlocks.YELLOW_METAL_WALL_HANGING_SIGN.get(), new Item.Properties().stacksTo(16)));

	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	@EventBusSubscriber(Dist.CLIENT)
	public static class ItemsClientSideHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public static void clientLoad(FMLClientSetupEvent event) {
			event.enqueueWork(() -> {
				ItemProperties.register(CRYSTALLITE_BOW.get(), ResourceLocation.parse("better_tools:crystallite_bow_pulling"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) CrystalliteBowPullStateProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(CRYSTALLITE_BOW_IRON.get(), ResourceLocation.parse("better_tools:crystallite_bow_iron_pulling"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) CrystalliteBowPullStateProcedure.execute(entity, itemStackToRender));
				ItemProperties.register(ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:energy_vial_energy"), (itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialEnergyValueProcedure.execute(itemStackToRender));
				ItemProperties.register(ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:energy_vial_active"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialActiveProcedure.execute(entity != null ? entity.level() : clientWorld, entity, itemStackToRender));
				ItemProperties.register(EMERALD_ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:emerald_energy_vial_energy"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialEnergyValueProcedure.execute(itemStackToRender));
				ItemProperties.register(EMERALD_ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:emerald_energy_vial_active"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialActiveProcedure.execute(entity != null ? entity.level() : clientWorld, entity, itemStackToRender));
				ItemProperties.register(NETHERITE_ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:netherite_energy_vial_energy"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialEnergyValueProcedure.execute(itemStackToRender));
				ItemProperties.register(NETHERITE_ENERGY_VIAL.get(), ResourceLocation.parse("better_tools:netherite_energy_vial_active"),
						(itemStackToRender, clientWorld, entity, itemEntityId) -> (float) EnergyVialActiveProcedure.execute(entity != null ? entity.level() : clientWorld, entity, itemStackToRender));
			});
		}
	}
}