package net.mcreator.bettertoolsandarmor.init;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.item.alchemy.PotionContents;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.core.component.DataComponents;

import mezz.jei.api.registration.IRecipeRegistration;
import mezz.jei.api.recipe.vanilla.IVanillaRecipeFactory;
import mezz.jei.api.recipe.vanilla.IJeiBrewingRecipe;
import mezz.jei.api.constants.RecipeTypes;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.IModPlugin;

import java.util.List;
import java.util.ArrayList;

@JeiPlugin
public class BetterToolsModBrewingRecipes implements IModPlugin {
	@Override
	public ResourceLocation getPluginUid() {
		return ResourceLocation.parse("better_tools:brewing_recipes");
	}

	@Override
	public void registerRecipes(IRecipeRegistration registration) {
		IVanillaRecipeFactory factory = registration.getVanillaRecipeFactory();
		List<IJeiBrewingRecipe> brewingRecipes = new ArrayList<>();
		ItemStack potion = new ItemStack(Items.POTION);
		ItemStack potion2 = new ItemStack(Items.POTION);
		List<ItemStack> ingredientStack = new ArrayList<>();
		List<ItemStack> inputStack = new ArrayList<>();
		ingredientStack.add(new ItemStack(Items.EXPERIENCE_BOTTLE));
		inputStack.add(new ItemStack(BetterToolsModItems.MYSTIC_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.EXPERIENCE_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(BetterToolsModBlocks.FOUR_LEAF_CLOVER.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LUCK));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(BetterToolsModBlocks.PURPLE_MUSHROOM.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FEATHER));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.SLOW_FALLING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LUCK));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.LUCK_POTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.LUCK_POTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LUCK));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.PRISMARINE_CRYSTALS));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.SWIFT_SWIM_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.KARMA_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(BetterToolsModItems.GUARDIAN_SPIKE.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.CRITICALITY_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FEATHER));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_SLOW_FALLING));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.DOUBLE_JUMP_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Blocks.WITHER_ROSE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY_2));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY_2));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.POTION_OF_DECAY));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.ENDER_PEARL));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LEAPING));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), new ItemStack(BetterToolsModItems.ASCENSION_POTION.get())));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FERMENTED_SPIDER_EYE));
		inputStack.add(new ItemStack(BetterToolsModItems.ASCENSION_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.DESCENSION_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.ENDER_PEARL));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.LONG_LEAPING));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), new ItemStack(BetterToolsModItems.ASCENSION_POTION.get())));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.ENDER_PEARL));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.STRONG_LEAPING));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), new ItemStack(BetterToolsModItems.ASCENSION_POTION.get())));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FERMENTED_SPIDER_EYE));
		inputStack.add(new ItemStack(BetterToolsModItems.LOST_SOULS_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.RECALL_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.ECHO_SHARD));
		inputStack.add(new ItemStack(BetterToolsModItems.MYSTIC_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.LOST_SOULS_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FERMENTED_SPIDER_EYE));
		inputStack.add(new ItemStack(BetterToolsModItems.DESCENSION_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.ASCENSION_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.FERMENTED_SPIDER_EYE));
		inputStack.add(new ItemStack(BetterToolsModItems.RECALL_POTION.get()));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), List.copyOf(inputStack), new ItemStack(BetterToolsModItems.LOST_SOULS_POTION.get())));
		inputStack.clear();
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(BetterToolsModItems.ULTRA_ENRICHED_BLAZE_POWDER.get()));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.WATER));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), new ItemStack(BetterToolsModItems.MYSTIC_POTION.get())));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.AMETHYST_SHARD));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(Potions.AWKWARD));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.ORE_VISION_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.REDSTONE));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.ORE_VISION_POTION));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.ORE_VISION_POTION_LONG));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		ingredientStack.add(new ItemStack(Items.GLOWSTONE_DUST));
		potion.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.ORE_VISION_POTION_LONG));
		potion2.set(DataComponents.POTION_CONTENTS, new PotionContents(BetterToolsModPotions.ORE_VISION_POTION));
		brewingRecipes.add(factory.createBrewingRecipe(List.copyOf(ingredientStack), potion.copy(), potion2.copy()));
		ingredientStack.clear();
		registration.addRecipes(RecipeTypes.BREWING, brewingRecipes);
	}
}