
/*
*    MCreator note: This file will be REGENERATED on each build.
*/
package net.mcreator.bettertoolsandarmor.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Block;

import net.mcreator.bettertoolsandarmor.block.sign.MetalWallSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalWallHangingSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalHangingSignBlock;
import net.mcreator.bettertoolsandarmor.block.TopazOreBlock;
import net.mcreator.bettertoolsandarmor.block.TopazBlockBlock;
import net.mcreator.bettertoolsandarmor.block.SugarBlockBlock;
import net.mcreator.bettertoolsandarmor.block.SapphireOreBlock;
import net.mcreator.bettertoolsandarmor.block.SapphireBlockBlock;
import net.mcreator.bettertoolsandarmor.block.RubyOreBlock;
import net.mcreator.bettertoolsandarmor.block.RubyBlockBlock;
import net.mcreator.bettertoolsandarmor.block.RandomOreBlock;
import net.mcreator.bettertoolsandarmor.block.PurpleMushroomBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PurpleMushroomBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedTopazWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedTopazTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedTopazStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedTopazSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedTopazBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRubyWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRubyTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRubyStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRubySlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRubyBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRedstoneWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRedstoneTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRedstoneStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRedstoneSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedRedstoneBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedNetherDiamondWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedNetherDiamondTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedNetherDiamondStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedNetherDiamondSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedNetherDiamondBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedGoldWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedGoldTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedGoldStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedGoldSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedGoldBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedDiamondWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedDiamondTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedDiamondStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedDiamondSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedDiamondBlockBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedAmethystWallBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedAmethystTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedAmethystStairsBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedAmethystSlabBlock;
import net.mcreator.bettertoolsandarmor.block.PolishedAmethystBlockBlock;
import net.mcreator.bettertoolsandarmor.block.NetherDiamondOreBlock;
import net.mcreator.bettertoolsandarmor.block.NetherDiamondBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedNetherDiamondWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedNetherDiamondTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedNetherDiamondStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedNetherDiamondSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedNetherDiamondBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedLapisWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedLapisTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedLapisStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedLapisSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedLapisBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedIronWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedIronTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedIronStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedIronSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedIronBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedGoldWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedGoldTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedGoldStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedGoldSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedGoldBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedEmeraldWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedEmeraldTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedEmeraldStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedEmeraldSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedEmeraldBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCopperWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCopperTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCopperStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCopperSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCopperBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCoalWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCoalTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCoalStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCoalSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedCoalBlockBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedAmethystWallBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedAmethystTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedAmethystStairsBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedAmethystSlabBlock;
import net.mcreator.bettertoolsandarmor.block.LightPolishedAmethystBlockBlock;
import net.mcreator.bettertoolsandarmor.block.JewelleryTableBlock;
import net.mcreator.bettertoolsandarmor.block.FourLeafCloverBlock;
import net.mcreator.bettertoolsandarmor.block.FlintBlockwoodBlock;
import net.mcreator.bettertoolsandarmor.block.EndTitaniumOreBlock;
import net.mcreator.bettertoolsandarmor.block.EndTitaniumBlockBlock;
import net.mcreator.bettertoolsandarmor.block.DeepslateRubyOreBlock;
import net.mcreator.bettertoolsandarmor.block.DeepslateRandomOreBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedLapisWallBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedLapisTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedLapisStairsBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedLapisSlabBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedLapisBlockBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedIronWallBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedIronTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedIronStairsBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedIronSlabBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedIronBlockBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedEmeraldWallBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedEmeraldTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedEmeraldStairsBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedEmeraldSlabBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedEmeraldBlockBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCopperWallBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCopperTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCopperStairsBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCopperSlabBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCopperBlockBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCoalWallBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCoalTrapdoorBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCoalStairsBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCoalSlabBlock;
import net.mcreator.bettertoolsandarmor.block.DarkPolishedCoalBlockBlock;
import net.mcreator.bettertoolsandarmor.block.CutCrystalliteBlockBlock;
import net.mcreator.bettertoolsandarmor.block.CrystalliteClusterAirBlock;
import net.mcreator.bettertoolsandarmor.block.CrystalliteBlockBlock;
import net.mcreator.bettertoolsandarmor.block.ClimbableWallBlock;
import net.mcreator.bettertoolsandarmor.block.ChargedIceOnBlock;
import net.mcreator.bettertoolsandarmor.block.BlueSlimeBlockBlock;
import net.mcreator.bettertoolsandarmor.block.BlueMushroomBlockBlock;
import net.mcreator.bettertoolsandarmor.block.BlueMushroomBlock;
import net.mcreator.bettertoolsandarmor.block.BlackstoneMagmaBlock;
import net.mcreator.bettertoolsandarmor.BetterToolsMod;

public class BetterToolsModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(BetterToolsMod.MODID);
	public static final DeferredBlock<Block> NETHER_DIAMOND_BLOCK = REGISTRY.register("nether_diamond_block", NetherDiamondBlockBlock::new);
	public static final DeferredBlock<Block> SUGAR_BLOCK = REGISTRY.register("sugar_block", SugarBlockBlock::new);
	public static final DeferredBlock<Block> RUBY_ORE = REGISTRY.register("ruby_ore", RubyOreBlock::new);
	public static final DeferredBlock<Block> RUBY_BLOCK = REGISTRY.register("ruby_block", RubyBlockBlock::new);
	public static final DeferredBlock<Block> RANDOM_ORE = REGISTRY.register("random_ore", RandomOreBlock::new);
	public static final DeferredBlock<Block> END_TITANIUM_ORE = REGISTRY.register("end_titanium_ore", EndTitaniumOreBlock::new);
	public static final DeferredBlock<Block> END_TITANIUM_BLOCK = REGISTRY.register("end_titanium_block", EndTitaniumBlockBlock::new);
	public static final DeferredBlock<Block> BLUE_SLIME_BLOCK = REGISTRY.register("blue_slime_block", BlueSlimeBlockBlock::new);
	public static final DeferredBlock<Block> BLUE_MUSHROOM = REGISTRY.register("blue_mushroom", BlueMushroomBlock::new);
	public static final DeferredBlock<Block> BLUE_MUSHROOM_BLOCK = REGISTRY.register("blue_mushroom_block", BlueMushroomBlockBlock::new);
	public static final DeferredBlock<Block> PURPLE_MUSHROOM = REGISTRY.register("purple_mushroom", PurpleMushroomBlock::new);
	public static final DeferredBlock<Block> PURPLE_MUSHROOM_BLOCK = REGISTRY.register("purple_mushroom_block", PurpleMushroomBlockBlock::new);
	public static final DeferredBlock<Block> BLACKSTONE_MAGMA = REGISTRY.register("blackstone_magma", BlackstoneMagmaBlock::new);
	public static final DeferredBlock<Block> CHARGED_ICE_ON = REGISTRY.register("charged_ice_on", ChargedIceOnBlock::new);
	public static final DeferredBlock<Block> SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", SapphireOreBlock::new);
	public static final DeferredBlock<Block> SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", SapphireBlockBlock::new);
	public static final DeferredBlock<Block> TOPAZ_ORE = REGISTRY.register("topaz_ore", TopazOreBlock::new);
	public static final DeferredBlock<Block> TOPAZ_BLOCK = REGISTRY.register("topaz_block", TopazBlockBlock::new);
	public static final DeferredBlock<Block> FOUR_LEAF_CLOVER = REGISTRY.register("four_leaf_clover", FourLeafCloverBlock::new);
	public static final DeferredBlock<Block> NETHER_DIAMOND_ORE = REGISTRY.register("nether_diamond_ore", NetherDiamondOreBlock::new);
	public static final DeferredBlock<Block> CRYSTALLITE_BLOCK = REGISTRY.register("crystallite_block", CrystalliteBlockBlock::new);
	public static final DeferredBlock<Block> CUT_CRYSTALLITE_BLOCK = REGISTRY.register("cut_crystallite_block", CutCrystalliteBlockBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_RUBY_ORE = REGISTRY.register("deepslate_ruby_ore", DeepslateRubyOreBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_RANDOM_ORE = REGISTRY.register("deepslate_random_ore", DeepslateRandomOreBlock::new);
	public static final DeferredBlock<Block> FLINT_BLOCKWOOD = REGISTRY.register("flint_blockwood", FlintBlockwoodBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_BLOCK = REGISTRY.register("dark_polished_coal_block", DarkPolishedCoalBlockBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_SLAB = REGISTRY.register("dark_polished_coal_slab", DarkPolishedCoalSlabBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_STAIRS = REGISTRY.register("dark_polished_coal_stairs", DarkPolishedCoalStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_BLOCK = REGISTRY.register("light_polished_coal_block", LightPolishedCoalBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_SLAB = REGISTRY.register("light_polished_coal_slab", LightPolishedCoalSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_STAIRS = REGISTRY.register("light_polished_coal_stairs", LightPolishedCoalStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_BLOCK = REGISTRY.register("light_polished_iron_block", LightPolishedIronBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_SLAB = REGISTRY.register("light_polished_iron_slab", LightPolishedIronSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_STAIRS = REGISTRY.register("light_polished_iron_stairs", LightPolishedIronStairsBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_BLOCK = REGISTRY.register("dark_polished_iron_block", DarkPolishedIronBlockBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_SLAB = REGISTRY.register("dark_polished_iron_slab", DarkPolishedIronSlabBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_STAIRS = REGISTRY.register("dark_polished_iron_stairs", DarkPolishedIronStairsBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_BLOCK = REGISTRY.register("dark_polished_lapis_block", DarkPolishedLapisBlockBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_SLAB = REGISTRY.register("dark_polished_lapis_slab", DarkPolishedLapisSlabBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_STAIRS = REGISTRY.register("dark_polished_lapis_stairs", DarkPolishedLapisStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_BLOCK = REGISTRY.register("light_polished_lapis_block", LightPolishedLapisBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_SLAB = REGISTRY.register("light_polished_lapis_slab", LightPolishedLapisSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_STAIRS = REGISTRY.register("light_polished_lapis_stairs", LightPolishedLapisStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_DIAMOND_BLOCK = REGISTRY.register("polished_diamond_block", PolishedDiamondBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_DIAMOND_SLAB = REGISTRY.register("polished_diamond_slab", PolishedDiamondSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_DIAMOND_STAIRS = REGISTRY.register("polished_diamond_stairs", PolishedDiamondStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_BLOCK = REGISTRY.register("light_polished_emerald_block", LightPolishedEmeraldBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_SLAB = REGISTRY.register("light_polished_emerald_slab", LightPolishedEmeraldSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_STAIRS = REGISTRY.register("light_polished_emerald_stairs", LightPolishedEmeraldStairsBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_BLOCK = REGISTRY.register("dark_polished_emerald_block", DarkPolishedEmeraldBlockBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_SLAB = REGISTRY.register("dark_polished_emerald_slab", DarkPolishedEmeraldSlabBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_STAIRS = REGISTRY.register("dark_polished_emerald_stairs", DarkPolishedEmeraldStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_REDSTONE_BLOCK = REGISTRY.register("polished_redstone_block", PolishedRedstoneBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_REDSTONE_SLAB = REGISTRY.register("polished_redstone_slab", PolishedRedstoneSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_REDSTONE_STAIRS = REGISTRY.register("polished_redstone_stairs", PolishedRedstoneStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_RUBY_BLOCK = REGISTRY.register("polished_ruby_block", PolishedRubyBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_RUBY_SLAB = REGISTRY.register("polished_ruby_slab", PolishedRubySlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_RUBY_STAIRS = REGISTRY.register("polished_ruby_stairs", PolishedRubyStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_BLOCK = REGISTRY.register("light_polished_copper_block", LightPolishedCopperBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_SLAB = REGISTRY.register("light_polished_copper_slab", LightPolishedCopperSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_STAIRS = REGISTRY.register("light_polished_copper_stairs", LightPolishedCopperStairsBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_BLOCK = REGISTRY.register("dark_polished_copper_block", DarkPolishedCopperBlockBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_SLAB = REGISTRY.register("dark_polished_copper_slab", DarkPolishedCopperSlabBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_STAIRS = REGISTRY.register("dark_polished_copper_stairs", DarkPolishedCopperStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_TOPAZ_BLOCK = REGISTRY.register("polished_topaz_block", PolishedTopazBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_TOPAZ_SLAB = REGISTRY.register("polished_topaz_slab", PolishedTopazSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_TOPAZ_STAIRS = REGISTRY.register("polished_topaz_stairs", PolishedTopazStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_GOLD_BLOCK = REGISTRY.register("polished_gold_block", PolishedGoldBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_GOLD_SLAB = REGISTRY.register("polished_gold_slab", PolishedGoldSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_GOLD_STAIRS = REGISTRY.register("polished_gold_stairs", PolishedGoldStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_BLOCK = REGISTRY.register("light_polished_gold_block", LightPolishedGoldBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_SLAB = REGISTRY.register("light_polished_gold_slab", LightPolishedGoldSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_STAIRS = REGISTRY.register("light_polished_gold_stairs", LightPolishedGoldStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_BLOCK = REGISTRY.register("polished_nether_diamond_block", PolishedNetherDiamondBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_SLAB = REGISTRY.register("polished_nether_diamond_slab", PolishedNetherDiamondSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_STAIRS = REGISTRY.register("polished_nether_diamond_stairs", PolishedNetherDiamondStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_BLOCK = REGISTRY.register("light_polished_nether_diamond_block", LightPolishedNetherDiamondBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_SLAB = REGISTRY.register("light_polished_nether_diamond_slab", LightPolishedNetherDiamondSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_STAIRS = REGISTRY.register("light_polished_nether_diamond_stairs", LightPolishedNetherDiamondStairsBlock::new);
	public static final DeferredBlock<Block> POLISHED_AMETHYST_BLOCK = REGISTRY.register("polished_amethyst_block", PolishedAmethystBlockBlock::new);
	public static final DeferredBlock<Block> POLISHED_AMETHYST_SLAB = REGISTRY.register("polished_amethyst_slab", PolishedAmethystSlabBlock::new);
	public static final DeferredBlock<Block> POLISHED_AMETHYST_STAIRS = REGISTRY.register("polished_amethyst_stairs", PolishedAmethystStairsBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_BLOCK = REGISTRY.register("light_polished_amethyst_block", LightPolishedAmethystBlockBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_SLAB = REGISTRY.register("light_polished_amethyst_slab", LightPolishedAmethystSlabBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_STAIRS = REGISTRY.register("light_polished_amethyst_stairs", LightPolishedAmethystStairsBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_TRAPDOOR = REGISTRY.register("dark_polished_coal_trapdoor", DarkPolishedCoalTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_TRAPDOOR = REGISTRY.register("light_polished_coal_trapdoor", LightPolishedCoalTrapdoorBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_TRAPDOOR = REGISTRY.register("dark_polished_iron_trapdoor", DarkPolishedIronTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_TRAPDOOR = REGISTRY.register("light_polished_iron_trapdoor", LightPolishedIronTrapdoorBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_TRAPDOOR = REGISTRY.register("dark_polished_lapis_trapdoor", DarkPolishedLapisTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_TRAPDOOR = REGISTRY.register("light_polished_lapis_trapdoor", LightPolishedLapisTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_DIAMOND_TRAPDOOR = REGISTRY.register("polished_diamond_trapdoor", PolishedDiamondTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_TRAPDOOR = REGISTRY.register("light_polished_emerald_trapdoor", LightPolishedEmeraldTrapdoorBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_TRAPDOOR = REGISTRY.register("dark_polished_emerald_trapdoor", DarkPolishedEmeraldTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_REDSTONE_TRAPDOOR = REGISTRY.register("polished_redstone_trapdoor", PolishedRedstoneTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_RUBY_TRAPDOOR = REGISTRY.register("polished_ruby_trapdoor", PolishedRubyTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_TRAPDOOR = REGISTRY.register("light_polished_copper_trapdoor", LightPolishedCopperTrapdoorBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_TRAPDOOR = REGISTRY.register("dark_polished_copper_trapdoor", DarkPolishedCopperTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_TOPAZ_TRAPDOOR = REGISTRY.register("polished_topaz_trapdoor", PolishedTopazTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_GOLD_TRAPDOOR = REGISTRY.register("polished_gold_trapdoor", PolishedGoldTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_TRAPDOOR = REGISTRY.register("light_polished_gold_trapdoor", LightPolishedGoldTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_TRAPDOOR = REGISTRY.register("polished_nether_diamond_trapdoor", PolishedNetherDiamondTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR = REGISTRY.register("light_polished_nether_diamond_trapdoor", LightPolishedNetherDiamondTrapdoorBlock::new);
	public static final DeferredBlock<Block> POLISHED_AMETHYST_TRAPDOOR = REGISTRY.register("polished_amethyst_trapdoor", PolishedAmethystTrapdoorBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_TRAPDOOR = REGISTRY.register("light_polished_amethyst_trapdoor", LightPolishedAmethystTrapdoorBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_WALL = REGISTRY.register("dark_polished_coal_wall", DarkPolishedCoalWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_WALL = REGISTRY.register("light_polished_coal_wall", LightPolishedCoalWallBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_WALL = REGISTRY.register("dark_polished_iron_wall", DarkPolishedIronWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_WALL = REGISTRY.register("light_polished_iron_wall", LightPolishedIronWallBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_WALL = REGISTRY.register("dark_polished_lapis_wall", DarkPolishedLapisWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_WALL = REGISTRY.register("light_polished_lapis_wall", LightPolishedLapisWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_DIAMOND_WALL = REGISTRY.register("polished_diamond_wall", PolishedDiamondWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_WALL = REGISTRY.register("light_polished_emerald_wall", LightPolishedEmeraldWallBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_WALL = REGISTRY.register("dark_polished_emerald_wall", DarkPolishedEmeraldWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_REDSTONE_WALL = REGISTRY.register("polished_redstone_wall", PolishedRedstoneWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_RUBY_WALL = REGISTRY.register("polished_ruby_wall", PolishedRubyWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_WALL = REGISTRY.register("light_polished_copper_wall", LightPolishedCopperWallBlock::new);
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_WALL = REGISTRY.register("dark_polished_copper_wall", DarkPolishedCopperWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_TOPAZ_WALL = REGISTRY.register("polished_topaz_wall", PolishedTopazWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_GOLD_WALL = REGISTRY.register("polished_gold_wall", PolishedGoldWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_WALL = REGISTRY.register("light_polished_gold_wall", LightPolishedGoldWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_WALL = REGISTRY.register("polished_nether_diamond_wall", PolishedNetherDiamondWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_WALL = REGISTRY.register("light_polished_nether_diamond_wall", LightPolishedNetherDiamondWallBlock::new);
	public static final DeferredBlock<Block> POLISHED_AMETHYST_WALL = REGISTRY.register("polished_amethyst_wall", PolishedAmethystWallBlock::new);
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_WALL = REGISTRY.register("light_polished_amethyst_wall", LightPolishedAmethystWallBlock::new);
	public static final DeferredBlock<Block> CRYSTALLITE_CLUSTER_AIR = REGISTRY.register("crystallite_cluster_air", CrystalliteClusterAirBlock::new);
	public static final DeferredBlock<Block> CLIMBABLE_WALL = REGISTRY.register("climbable_wall", ClimbableWallBlock::new);
	public static final DeferredBlock<Block> JEWELLERY_TABLE = REGISTRY.register("jewellery_table", JewelleryTableBlock::new);
	// Start of user code block custom blocks
	public static final BlockBehaviour.Properties METAL_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_WALL_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WALL_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_HANGING_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_HANGING_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_WALL_HANGING_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WALL_HANGING_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final DeferredBlock<Block> BLACK_METAL_SIGN = REGISTRY.register("black_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_WALL_SIGN = REGISTRY.register("black_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_HANGING_SIGN = REGISTRY.register("black_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_WALL_HANGING_SIGN = REGISTRY.register("black_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_SIGN = REGISTRY.register("gray_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_WALL_SIGN = REGISTRY.register("gray_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_HANGING_SIGN = REGISTRY.register("gray_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_WALL_HANGING_SIGN = REGISTRY.register("gray_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_SIGN = REGISTRY.register("blue_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_WALL_SIGN = REGISTRY.register("blue_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_HANGING_SIGN = REGISTRY.register("blue_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_WALL_HANGING_SIGN = REGISTRY.register("blue_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_SIGN = REGISTRY.register("brown_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_WALL_SIGN = REGISTRY.register("brown_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_HANGING_SIGN = REGISTRY.register("brown_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_WALL_HANGING_SIGN = REGISTRY.register("brown_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_SIGN = REGISTRY.register("cream_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_WALL_SIGN = REGISTRY.register("cream_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_HANGING_SIGN = REGISTRY.register("cream_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_WALL_HANGING_SIGN = REGISTRY.register("cream_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_SIGN = REGISTRY.register("cyan_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_WALL_SIGN = REGISTRY.register("cyan_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_HANGING_SIGN = REGISTRY.register("cyan_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_WALL_HANGING_SIGN = REGISTRY.register("cyan_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_SIGN = REGISTRY.register("dark_orange_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_WALL_SIGN = REGISTRY.register("dark_orange_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_HANGING_SIGN = REGISTRY.register("dark_orange_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_orange_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_SIGN = REGISTRY.register("dark_pink_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_WALL_SIGN = REGISTRY.register("dark_pink_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_HANGING_SIGN = REGISTRY.register("dark_pink_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_pink_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_SIGN = REGISTRY.register("dark_red_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_WALL_SIGN = REGISTRY.register("dark_red_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_HANGING_SIGN = REGISTRY.register("dark_red_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_red_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_SIGN = REGISTRY.register("green_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_WALL_SIGN = REGISTRY.register("green_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_HANGING_SIGN = REGISTRY.register("green_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_WALL_HANGING_SIGN = REGISTRY.register("green_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_SIGN = REGISTRY.register("light_blue_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_WALL_SIGN = REGISTRY.register("light_blue_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_HANGING_SIGN = REGISTRY.register("light_blue_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_WALL_HANGING_SIGN = REGISTRY.register("light_blue_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_SIGN = REGISTRY.register("light_gray_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_WALL_SIGN = REGISTRY.register("light_gray_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_HANGING_SIGN = REGISTRY.register("light_gray_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_WALL_HANGING_SIGN = REGISTRY.register("light_gray_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_SIGN = REGISTRY.register("lime_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_WALL_SIGN = REGISTRY.register("lime_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_HANGING_SIGN = REGISTRY.register("lime_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_WALL_HANGING_SIGN = REGISTRY.register("lime_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_SIGN = REGISTRY.register("magenta_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_WALL_SIGN = REGISTRY.register("magenta_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_HANGING_SIGN = REGISTRY.register("magenta_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_WALL_HANGING_SIGN = REGISTRY.register("magenta_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_SIGN = REGISTRY.register("orange_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_WALL_SIGN = REGISTRY.register("orange_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_HANGING_SIGN = REGISTRY.register("orange_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_WALL_HANGING_SIGN = REGISTRY.register("orange_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_SIGN = REGISTRY.register("pink_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_WALL_SIGN = REGISTRY.register("pink_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_HANGING_SIGN = REGISTRY.register("pink_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_WALL_HANGING_SIGN = REGISTRY.register("pink_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_SIGN = REGISTRY.register("purple_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_WALL_SIGN = REGISTRY.register("purple_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_HANGING_SIGN = REGISTRY.register("purple_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_WALL_HANGING_SIGN = REGISTRY.register("purple_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_SIGN = REGISTRY.register("red_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_WALL_SIGN = REGISTRY.register("red_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_HANGING_SIGN = REGISTRY.register("red_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_WALL_HANGING_SIGN = REGISTRY.register("red_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_SIGN = REGISTRY.register("white_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_WALL_SIGN = REGISTRY.register("white_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_HANGING_SIGN = REGISTRY.register("white_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_WALL_HANGING_SIGN = REGISTRY.register("white_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_SIGN = REGISTRY.register("yellow_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_WALL_SIGN = REGISTRY.register("yellow_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_HANGING_SIGN = REGISTRY.register("yellow_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_WALL_HANGING_SIGN = REGISTRY.register("yellow_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	// End of user code block custom blocks
}
