/*
*    MCreator note: This file will be REGENERATED on each build.
*/
package net.mcreator.bettertoolsandarmor.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.Block;

import net.mcreator.bettertoolsandarmor.block.sign.MetalWallSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalWallHangingSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalSignBlock;
import net.mcreator.bettertoolsandarmor.block.sign.MetalHangingSignBlock;
import net.mcreator.bettertoolsandarmor.block.*;
import net.mcreator.bettertoolsandarmor.BetterToolsMod;

public class BetterToolsModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(BetterToolsMod.MODID);
	public static final DeferredBlock<Block> NETHER_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> SUGAR_BLOCK;
	public static final DeferredBlock<Block> RUBY_ORE;
	public static final DeferredBlock<Block> RUBY_BLOCK;
	public static final DeferredBlock<Block> RANDOM_ORE;
	public static final DeferredBlock<Block> END_TITANIUM_ORE;
	public static final DeferredBlock<Block> END_TITANIUM_BLOCK;
	public static final DeferredBlock<Block> BLUE_SLIME_BLOCK;
	public static final DeferredBlock<Block> BLUE_MUSHROOM;
	public static final DeferredBlock<Block> BLUE_MUSHROOM_BLOCK;
	public static final DeferredBlock<Block> PURPLE_MUSHROOM;
	public static final DeferredBlock<Block> PURPLE_MUSHROOM_BLOCK;
	public static final DeferredBlock<Block> BLACKSTONE_MAGMA;
	public static final DeferredBlock<Block> CHARGED_ICE_ON;
	public static final DeferredBlock<Block> SAPPHIRE_ORE;
	public static final DeferredBlock<Block> SAPPHIRE_BLOCK;
	public static final DeferredBlock<Block> TOPAZ_ORE;
	public static final DeferredBlock<Block> TOPAZ_BLOCK;
	public static final DeferredBlock<Block> FOUR_LEAF_CLOVER;
	public static final DeferredBlock<Block> NETHER_DIAMOND_ORE;
	public static final DeferredBlock<Block> CRYSTALLITE_BLOCK;
	public static final DeferredBlock<Block> CUT_CRYSTALLITE_BLOCK;
	public static final DeferredBlock<Block> DEEPSLATE_RUBY_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_RANDOM_ORE;
	public static final DeferredBlock<Block> FLINT_BLOCKWOOD;
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_BLOCK;
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_SLAB;
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_STAIRS;
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_BLOCK;
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_SLAB;
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_STAIRS;
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_BLOCK;
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_SLAB;
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_STAIRS;
	public static final DeferredBlock<Block> POLISHED_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> POLISHED_DIAMOND_SLAB;
	public static final DeferredBlock<Block> POLISHED_DIAMOND_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_STAIRS;
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_BLOCK;
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_SLAB;
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_STAIRS;
	public static final DeferredBlock<Block> POLISHED_REDSTONE_BLOCK;
	public static final DeferredBlock<Block> POLISHED_REDSTONE_SLAB;
	public static final DeferredBlock<Block> POLISHED_REDSTONE_STAIRS;
	public static final DeferredBlock<Block> POLISHED_RUBY_BLOCK;
	public static final DeferredBlock<Block> POLISHED_RUBY_SLAB;
	public static final DeferredBlock<Block> POLISHED_RUBY_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_STAIRS;
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_BLOCK;
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_SLAB;
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_STAIRS;
	public static final DeferredBlock<Block> POLISHED_TOPAZ_BLOCK;
	public static final DeferredBlock<Block> POLISHED_TOPAZ_SLAB;
	public static final DeferredBlock<Block> POLISHED_TOPAZ_STAIRS;
	public static final DeferredBlock<Block> POLISHED_GOLD_BLOCK;
	public static final DeferredBlock<Block> POLISHED_GOLD_SLAB;
	public static final DeferredBlock<Block> POLISHED_GOLD_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_STAIRS;
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_SLAB;
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_STAIRS;
	public static final DeferredBlock<Block> POLISHED_AMETHYST_BLOCK;
	public static final DeferredBlock<Block> POLISHED_AMETHYST_SLAB;
	public static final DeferredBlock<Block> POLISHED_AMETHYST_STAIRS;
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_BLOCK;
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_SLAB;
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_STAIRS;
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_TRAPDOOR;
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_TRAPDOOR;
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_DIAMOND_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_TRAPDOOR;
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_REDSTONE_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_RUBY_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_TRAPDOOR;
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_TOPAZ_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_GOLD_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR;
	public static final DeferredBlock<Block> POLISHED_AMETHYST_TRAPDOOR;
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_TRAPDOOR;
	public static final DeferredBlock<Block> DARK_POLISHED_COAL_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COAL_WALL;
	public static final DeferredBlock<Block> DARK_POLISHED_IRON_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_IRON_WALL;
	public static final DeferredBlock<Block> DARK_POLISHED_LAPIS_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_LAPIS_WALL;
	public static final DeferredBlock<Block> POLISHED_DIAMOND_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_EMERALD_WALL;
	public static final DeferredBlock<Block> DARK_POLISHED_EMERALD_WALL;
	public static final DeferredBlock<Block> POLISHED_REDSTONE_WALL;
	public static final DeferredBlock<Block> POLISHED_RUBY_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_COPPER_WALL;
	public static final DeferredBlock<Block> DARK_POLISHED_COPPER_WALL;
	public static final DeferredBlock<Block> POLISHED_TOPAZ_WALL;
	public static final DeferredBlock<Block> POLISHED_GOLD_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_GOLD_WALL;
	public static final DeferredBlock<Block> POLISHED_NETHER_DIAMOND_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_NETHER_DIAMOND_WALL;
	public static final DeferredBlock<Block> POLISHED_AMETHYST_WALL;
	public static final DeferredBlock<Block> LIGHT_POLISHED_AMETHYST_WALL;
	public static final DeferredBlock<Block> CRYSTALLITE_CLUSTER_AIR;
	public static final DeferredBlock<Block> CLIMBABLE_WALL;
	public static final DeferredBlock<Block> JEWELLERY_TABLE;
	static {
		NETHER_DIAMOND_BLOCK = REGISTRY.register("nether_diamond_block", NetherDiamondBlockBlock::new);
		SUGAR_BLOCK = REGISTRY.register("sugar_block", SugarBlockBlock::new);
		RUBY_ORE = REGISTRY.register("ruby_ore", RubyOreBlock::new);
		RUBY_BLOCK = REGISTRY.register("ruby_block", RubyBlockBlock::new);
		RANDOM_ORE = REGISTRY.register("random_ore", RandomOreBlock::new);
		END_TITANIUM_ORE = REGISTRY.register("end_titanium_ore", EndTitaniumOreBlock::new);
		END_TITANIUM_BLOCK = REGISTRY.register("end_titanium_block", EndTitaniumBlockBlock::new);
		BLUE_SLIME_BLOCK = REGISTRY.register("blue_slime_block", BlueSlimeBlockBlock::new);
		BLUE_MUSHROOM = REGISTRY.register("blue_mushroom", BlueMushroomBlock::new);
		BLUE_MUSHROOM_BLOCK = REGISTRY.register("blue_mushroom_block", BlueMushroomBlockBlock::new);
		PURPLE_MUSHROOM = REGISTRY.register("purple_mushroom", PurpleMushroomBlock::new);
		PURPLE_MUSHROOM_BLOCK = REGISTRY.register("purple_mushroom_block", PurpleMushroomBlockBlock::new);
		BLACKSTONE_MAGMA = REGISTRY.register("blackstone_magma", BlackstoneMagmaBlock::new);
		CHARGED_ICE_ON = REGISTRY.register("charged_ice_on", ChargedIceOnBlock::new);
		SAPPHIRE_ORE = REGISTRY.register("sapphire_ore", SapphireOreBlock::new);
		SAPPHIRE_BLOCK = REGISTRY.register("sapphire_block", SapphireBlockBlock::new);
		TOPAZ_ORE = REGISTRY.register("topaz_ore", TopazOreBlock::new);
		TOPAZ_BLOCK = REGISTRY.register("topaz_block", TopazBlockBlock::new);
		FOUR_LEAF_CLOVER = REGISTRY.register("four_leaf_clover", FourLeafCloverBlock::new);
		NETHER_DIAMOND_ORE = REGISTRY.register("nether_diamond_ore", NetherDiamondOreBlock::new);
		CRYSTALLITE_BLOCK = REGISTRY.register("crystallite_block", CrystalliteBlockBlock::new);
		CUT_CRYSTALLITE_BLOCK = REGISTRY.register("cut_crystallite_block", CutCrystalliteBlockBlock::new);
		DEEPSLATE_RUBY_ORE = REGISTRY.register("deepslate_ruby_ore", DeepslateRubyOreBlock::new);
		DEEPSLATE_RANDOM_ORE = REGISTRY.register("deepslate_random_ore", DeepslateRandomOreBlock::new);
		FLINT_BLOCKWOOD = REGISTRY.register("flint_blockwood", FlintBlockwoodBlock::new);
		DARK_POLISHED_COAL_BLOCK = REGISTRY.register("dark_polished_coal_block", DarkPolishedCoalBlockBlock::new);
		DARK_POLISHED_COAL_SLAB = REGISTRY.register("dark_polished_coal_slab", DarkPolishedCoalSlabBlock::new);
		DARK_POLISHED_COAL_STAIRS = REGISTRY.register("dark_polished_coal_stairs", DarkPolishedCoalStairsBlock::new);
		LIGHT_POLISHED_COAL_BLOCK = REGISTRY.register("light_polished_coal_block", LightPolishedCoalBlockBlock::new);
		LIGHT_POLISHED_COAL_SLAB = REGISTRY.register("light_polished_coal_slab", LightPolishedCoalSlabBlock::new);
		LIGHT_POLISHED_COAL_STAIRS = REGISTRY.register("light_polished_coal_stairs", LightPolishedCoalStairsBlock::new);
		LIGHT_POLISHED_IRON_BLOCK = REGISTRY.register("light_polished_iron_block", LightPolishedIronBlockBlock::new);
		LIGHT_POLISHED_IRON_SLAB = REGISTRY.register("light_polished_iron_slab", LightPolishedIronSlabBlock::new);
		LIGHT_POLISHED_IRON_STAIRS = REGISTRY.register("light_polished_iron_stairs", LightPolishedIronStairsBlock::new);
		DARK_POLISHED_IRON_BLOCK = REGISTRY.register("dark_polished_iron_block", DarkPolishedIronBlockBlock::new);
		DARK_POLISHED_IRON_SLAB = REGISTRY.register("dark_polished_iron_slab", DarkPolishedIronSlabBlock::new);
		DARK_POLISHED_IRON_STAIRS = REGISTRY.register("dark_polished_iron_stairs", DarkPolishedIronStairsBlock::new);
		DARK_POLISHED_LAPIS_BLOCK = REGISTRY.register("dark_polished_lapis_block", DarkPolishedLapisBlockBlock::new);
		DARK_POLISHED_LAPIS_SLAB = REGISTRY.register("dark_polished_lapis_slab", DarkPolishedLapisSlabBlock::new);
		DARK_POLISHED_LAPIS_STAIRS = REGISTRY.register("dark_polished_lapis_stairs", DarkPolishedLapisStairsBlock::new);
		LIGHT_POLISHED_LAPIS_BLOCK = REGISTRY.register("light_polished_lapis_block", LightPolishedLapisBlockBlock::new);
		LIGHT_POLISHED_LAPIS_SLAB = REGISTRY.register("light_polished_lapis_slab", LightPolishedLapisSlabBlock::new);
		LIGHT_POLISHED_LAPIS_STAIRS = REGISTRY.register("light_polished_lapis_stairs", LightPolishedLapisStairsBlock::new);
		POLISHED_DIAMOND_BLOCK = REGISTRY.register("polished_diamond_block", PolishedDiamondBlockBlock::new);
		POLISHED_DIAMOND_SLAB = REGISTRY.register("polished_diamond_slab", PolishedDiamondSlabBlock::new);
		POLISHED_DIAMOND_STAIRS = REGISTRY.register("polished_diamond_stairs", PolishedDiamondStairsBlock::new);
		LIGHT_POLISHED_EMERALD_BLOCK = REGISTRY.register("light_polished_emerald_block", LightPolishedEmeraldBlockBlock::new);
		LIGHT_POLISHED_EMERALD_SLAB = REGISTRY.register("light_polished_emerald_slab", LightPolishedEmeraldSlabBlock::new);
		LIGHT_POLISHED_EMERALD_STAIRS = REGISTRY.register("light_polished_emerald_stairs", LightPolishedEmeraldStairsBlock::new);
		DARK_POLISHED_EMERALD_BLOCK = REGISTRY.register("dark_polished_emerald_block", DarkPolishedEmeraldBlockBlock::new);
		DARK_POLISHED_EMERALD_SLAB = REGISTRY.register("dark_polished_emerald_slab", DarkPolishedEmeraldSlabBlock::new);
		DARK_POLISHED_EMERALD_STAIRS = REGISTRY.register("dark_polished_emerald_stairs", DarkPolishedEmeraldStairsBlock::new);
		POLISHED_REDSTONE_BLOCK = REGISTRY.register("polished_redstone_block", PolishedRedstoneBlockBlock::new);
		POLISHED_REDSTONE_SLAB = REGISTRY.register("polished_redstone_slab", PolishedRedstoneSlabBlock::new);
		POLISHED_REDSTONE_STAIRS = REGISTRY.register("polished_redstone_stairs", PolishedRedstoneStairsBlock::new);
		POLISHED_RUBY_BLOCK = REGISTRY.register("polished_ruby_block", PolishedRubyBlockBlock::new);
		POLISHED_RUBY_SLAB = REGISTRY.register("polished_ruby_slab", PolishedRubySlabBlock::new);
		POLISHED_RUBY_STAIRS = REGISTRY.register("polished_ruby_stairs", PolishedRubyStairsBlock::new);
		LIGHT_POLISHED_COPPER_BLOCK = REGISTRY.register("light_polished_copper_block", LightPolishedCopperBlockBlock::new);
		LIGHT_POLISHED_COPPER_SLAB = REGISTRY.register("light_polished_copper_slab", LightPolishedCopperSlabBlock::new);
		LIGHT_POLISHED_COPPER_STAIRS = REGISTRY.register("light_polished_copper_stairs", LightPolishedCopperStairsBlock::new);
		DARK_POLISHED_COPPER_BLOCK = REGISTRY.register("dark_polished_copper_block", DarkPolishedCopperBlockBlock::new);
		DARK_POLISHED_COPPER_SLAB = REGISTRY.register("dark_polished_copper_slab", DarkPolishedCopperSlabBlock::new);
		DARK_POLISHED_COPPER_STAIRS = REGISTRY.register("dark_polished_copper_stairs", DarkPolishedCopperStairsBlock::new);
		POLISHED_TOPAZ_BLOCK = REGISTRY.register("polished_topaz_block", PolishedTopazBlockBlock::new);
		POLISHED_TOPAZ_SLAB = REGISTRY.register("polished_topaz_slab", PolishedTopazSlabBlock::new);
		POLISHED_TOPAZ_STAIRS = REGISTRY.register("polished_topaz_stairs", PolishedTopazStairsBlock::new);
		POLISHED_GOLD_BLOCK = REGISTRY.register("polished_gold_block", PolishedGoldBlockBlock::new);
		POLISHED_GOLD_SLAB = REGISTRY.register("polished_gold_slab", PolishedGoldSlabBlock::new);
		POLISHED_GOLD_STAIRS = REGISTRY.register("polished_gold_stairs", PolishedGoldStairsBlock::new);
		LIGHT_POLISHED_GOLD_BLOCK = REGISTRY.register("light_polished_gold_block", LightPolishedGoldBlockBlock::new);
		LIGHT_POLISHED_GOLD_SLAB = REGISTRY.register("light_polished_gold_slab", LightPolishedGoldSlabBlock::new);
		LIGHT_POLISHED_GOLD_STAIRS = REGISTRY.register("light_polished_gold_stairs", LightPolishedGoldStairsBlock::new);
		POLISHED_NETHER_DIAMOND_BLOCK = REGISTRY.register("polished_nether_diamond_block", PolishedNetherDiamondBlockBlock::new);
		POLISHED_NETHER_DIAMOND_SLAB = REGISTRY.register("polished_nether_diamond_slab", PolishedNetherDiamondSlabBlock::new);
		POLISHED_NETHER_DIAMOND_STAIRS = REGISTRY.register("polished_nether_diamond_stairs", PolishedNetherDiamondStairsBlock::new);
		LIGHT_POLISHED_NETHER_DIAMOND_BLOCK = REGISTRY.register("light_polished_nether_diamond_block", LightPolishedNetherDiamondBlockBlock::new);
		LIGHT_POLISHED_NETHER_DIAMOND_SLAB = REGISTRY.register("light_polished_nether_diamond_slab", LightPolishedNetherDiamondSlabBlock::new);
		LIGHT_POLISHED_NETHER_DIAMOND_STAIRS = REGISTRY.register("light_polished_nether_diamond_stairs", LightPolishedNetherDiamondStairsBlock::new);
		POLISHED_AMETHYST_BLOCK = REGISTRY.register("polished_amethyst_block", PolishedAmethystBlockBlock::new);
		POLISHED_AMETHYST_SLAB = REGISTRY.register("polished_amethyst_slab", PolishedAmethystSlabBlock::new);
		POLISHED_AMETHYST_STAIRS = REGISTRY.register("polished_amethyst_stairs", PolishedAmethystStairsBlock::new);
		LIGHT_POLISHED_AMETHYST_BLOCK = REGISTRY.register("light_polished_amethyst_block", LightPolishedAmethystBlockBlock::new);
		LIGHT_POLISHED_AMETHYST_SLAB = REGISTRY.register("light_polished_amethyst_slab", LightPolishedAmethystSlabBlock::new);
		LIGHT_POLISHED_AMETHYST_STAIRS = REGISTRY.register("light_polished_amethyst_stairs", LightPolishedAmethystStairsBlock::new);
		DARK_POLISHED_COAL_TRAPDOOR = REGISTRY.register("dark_polished_coal_trapdoor", DarkPolishedCoalTrapdoorBlock::new);
		LIGHT_POLISHED_COAL_TRAPDOOR = REGISTRY.register("light_polished_coal_trapdoor", LightPolishedCoalTrapdoorBlock::new);
		DARK_POLISHED_IRON_TRAPDOOR = REGISTRY.register("dark_polished_iron_trapdoor", DarkPolishedIronTrapdoorBlock::new);
		LIGHT_POLISHED_IRON_TRAPDOOR = REGISTRY.register("light_polished_iron_trapdoor", LightPolishedIronTrapdoorBlock::new);
		DARK_POLISHED_LAPIS_TRAPDOOR = REGISTRY.register("dark_polished_lapis_trapdoor", DarkPolishedLapisTrapdoorBlock::new);
		LIGHT_POLISHED_LAPIS_TRAPDOOR = REGISTRY.register("light_polished_lapis_trapdoor", LightPolishedLapisTrapdoorBlock::new);
		POLISHED_DIAMOND_TRAPDOOR = REGISTRY.register("polished_diamond_trapdoor", PolishedDiamondTrapdoorBlock::new);
		LIGHT_POLISHED_EMERALD_TRAPDOOR = REGISTRY.register("light_polished_emerald_trapdoor", LightPolishedEmeraldTrapdoorBlock::new);
		DARK_POLISHED_EMERALD_TRAPDOOR = REGISTRY.register("dark_polished_emerald_trapdoor", DarkPolishedEmeraldTrapdoorBlock::new);
		POLISHED_REDSTONE_TRAPDOOR = REGISTRY.register("polished_redstone_trapdoor", PolishedRedstoneTrapdoorBlock::new);
		POLISHED_RUBY_TRAPDOOR = REGISTRY.register("polished_ruby_trapdoor", PolishedRubyTrapdoorBlock::new);
		LIGHT_POLISHED_COPPER_TRAPDOOR = REGISTRY.register("light_polished_copper_trapdoor", LightPolishedCopperTrapdoorBlock::new);
		DARK_POLISHED_COPPER_TRAPDOOR = REGISTRY.register("dark_polished_copper_trapdoor", DarkPolishedCopperTrapdoorBlock::new);
		POLISHED_TOPAZ_TRAPDOOR = REGISTRY.register("polished_topaz_trapdoor", PolishedTopazTrapdoorBlock::new);
		POLISHED_GOLD_TRAPDOOR = REGISTRY.register("polished_gold_trapdoor", PolishedGoldTrapdoorBlock::new);
		LIGHT_POLISHED_GOLD_TRAPDOOR = REGISTRY.register("light_polished_gold_trapdoor", LightPolishedGoldTrapdoorBlock::new);
		POLISHED_NETHER_DIAMOND_TRAPDOOR = REGISTRY.register("polished_nether_diamond_trapdoor", PolishedNetherDiamondTrapdoorBlock::new);
		LIGHT_POLISHED_NETHER_DIAMOND_TRAPDOOR = REGISTRY.register("light_polished_nether_diamond_trapdoor", LightPolishedNetherDiamondTrapdoorBlock::new);
		POLISHED_AMETHYST_TRAPDOOR = REGISTRY.register("polished_amethyst_trapdoor", PolishedAmethystTrapdoorBlock::new);
		LIGHT_POLISHED_AMETHYST_TRAPDOOR = REGISTRY.register("light_polished_amethyst_trapdoor", LightPolishedAmethystTrapdoorBlock::new);
		DARK_POLISHED_COAL_WALL = REGISTRY.register("dark_polished_coal_wall", DarkPolishedCoalWallBlock::new);
		LIGHT_POLISHED_COAL_WALL = REGISTRY.register("light_polished_coal_wall", LightPolishedCoalWallBlock::new);
		DARK_POLISHED_IRON_WALL = REGISTRY.register("dark_polished_iron_wall", DarkPolishedIronWallBlock::new);
		LIGHT_POLISHED_IRON_WALL = REGISTRY.register("light_polished_iron_wall", LightPolishedIronWallBlock::new);
		DARK_POLISHED_LAPIS_WALL = REGISTRY.register("dark_polished_lapis_wall", DarkPolishedLapisWallBlock::new);
		LIGHT_POLISHED_LAPIS_WALL = REGISTRY.register("light_polished_lapis_wall", LightPolishedLapisWallBlock::new);
		POLISHED_DIAMOND_WALL = REGISTRY.register("polished_diamond_wall", PolishedDiamondWallBlock::new);
		LIGHT_POLISHED_EMERALD_WALL = REGISTRY.register("light_polished_emerald_wall", LightPolishedEmeraldWallBlock::new);
		DARK_POLISHED_EMERALD_WALL = REGISTRY.register("dark_polished_emerald_wall", DarkPolishedEmeraldWallBlock::new);
		POLISHED_REDSTONE_WALL = REGISTRY.register("polished_redstone_wall", PolishedRedstoneWallBlock::new);
		POLISHED_RUBY_WALL = REGISTRY.register("polished_ruby_wall", PolishedRubyWallBlock::new);
		LIGHT_POLISHED_COPPER_WALL = REGISTRY.register("light_polished_copper_wall", LightPolishedCopperWallBlock::new);
		DARK_POLISHED_COPPER_WALL = REGISTRY.register("dark_polished_copper_wall", DarkPolishedCopperWallBlock::new);
		POLISHED_TOPAZ_WALL = REGISTRY.register("polished_topaz_wall", PolishedTopazWallBlock::new);
		POLISHED_GOLD_WALL = REGISTRY.register("polished_gold_wall", PolishedGoldWallBlock::new);
		LIGHT_POLISHED_GOLD_WALL = REGISTRY.register("light_polished_gold_wall", LightPolishedGoldWallBlock::new);
		POLISHED_NETHER_DIAMOND_WALL = REGISTRY.register("polished_nether_diamond_wall", PolishedNetherDiamondWallBlock::new);
		LIGHT_POLISHED_NETHER_DIAMOND_WALL = REGISTRY.register("light_polished_nether_diamond_wall", LightPolishedNetherDiamondWallBlock::new);
		POLISHED_AMETHYST_WALL = REGISTRY.register("polished_amethyst_wall", PolishedAmethystWallBlock::new);
		LIGHT_POLISHED_AMETHYST_WALL = REGISTRY.register("light_polished_amethyst_wall", LightPolishedAmethystWallBlock::new);
		CRYSTALLITE_CLUSTER_AIR = REGISTRY.register("crystallite_cluster_air", CrystalliteClusterAirBlock::new);
		CLIMBABLE_WALL = REGISTRY.register("climbable_wall", ClimbableWallBlock::new);
		JEWELLERY_TABLE = REGISTRY.register("jewellery_table", JewelleryTableBlock::new);
	}
	// Start of user code block custom blocks
	public static final BlockBehaviour.Properties METAL_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_WALL_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WALL_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_HANGING_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_HANGING_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final BlockBehaviour.Properties METAL_WALL_HANGING_SIGN_PROPERTIES = BlockBehaviour.Properties.ofFullCopy(Blocks.OAK_WALL_HANGING_SIGN).explosionResistance(6).destroyTime(2).sound(SoundType.METAL);
	public static final DeferredBlock<Block> BLACK_METAL_SIGN = REGISTRY.register("black_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_WALL_SIGN = REGISTRY.register("black_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_HANGING_SIGN = REGISTRY.register("black_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> BLACK_METAL_WALL_HANGING_SIGN = REGISTRY.register("black_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLACK_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_SIGN = REGISTRY.register("gray_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_WALL_SIGN = REGISTRY.register("gray_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_HANGING_SIGN = REGISTRY.register("gray_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> GRAY_METAL_WALL_HANGING_SIGN = REGISTRY.register("gray_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_SIGN = REGISTRY.register("blue_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_WALL_SIGN = REGISTRY.register("blue_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_HANGING_SIGN = REGISTRY.register("blue_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BLUE_METAL_WALL_HANGING_SIGN = REGISTRY.register("blue_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_SIGN = REGISTRY.register("brown_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_WALL_SIGN = REGISTRY.register("brown_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_HANGING_SIGN = REGISTRY.register("brown_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> BROWN_METAL_WALL_HANGING_SIGN = REGISTRY.register("brown_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.BROWN_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_SIGN = REGISTRY.register("cream_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_WALL_SIGN = REGISTRY.register("cream_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_HANGING_SIGN = REGISTRY.register("cream_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CREAM_METAL_WALL_HANGING_SIGN = REGISTRY.register("cream_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CREAM_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_SIGN = REGISTRY.register("cyan_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_WALL_SIGN = REGISTRY.register("cyan_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_HANGING_SIGN = REGISTRY.register("cyan_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> CYAN_METAL_WALL_HANGING_SIGN = REGISTRY.register("cyan_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.CYAN_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_SIGN = REGISTRY.register("dark_orange_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_WALL_SIGN = REGISTRY.register("dark_orange_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_HANGING_SIGN = REGISTRY.register("dark_orange_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_ORANGE_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_orange_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_SIGN = REGISTRY.register("dark_pink_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_WALL_SIGN = REGISTRY.register("dark_pink_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_HANGING_SIGN = REGISTRY.register("dark_pink_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_PINK_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_pink_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_PINK_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_SIGN = REGISTRY.register("dark_red_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_WALL_SIGN = REGISTRY.register("dark_red_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_HANGING_SIGN = REGISTRY.register("dark_red_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> DARK_RED_METAL_WALL_HANGING_SIGN = REGISTRY.register("dark_red_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.DARK_RED_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_SIGN = REGISTRY.register("green_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_WALL_SIGN = REGISTRY.register("green_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_HANGING_SIGN = REGISTRY.register("green_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> GREEN_METAL_WALL_HANGING_SIGN = REGISTRY.register("green_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.GREEN_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_SIGN = REGISTRY.register("light_blue_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_WALL_SIGN = REGISTRY.register("light_blue_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_HANGING_SIGN = REGISTRY.register("light_blue_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_BLUE_METAL_WALL_HANGING_SIGN = REGISTRY.register("light_blue_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_BLUE_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_SIGN = REGISTRY.register("light_gray_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_WALL_SIGN = REGISTRY.register("light_gray_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_HANGING_SIGN = REGISTRY.register("light_gray_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIGHT_GRAY_METAL_WALL_HANGING_SIGN = REGISTRY.register("light_gray_metal_wall_hanging_sign",
			() -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIGHT_GRAY_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_SIGN = REGISTRY.register("lime_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_WALL_SIGN = REGISTRY.register("lime_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_HANGING_SIGN = REGISTRY.register("lime_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> LIME_METAL_WALL_HANGING_SIGN = REGISTRY.register("lime_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.LIME_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_SIGN = REGISTRY.register("magenta_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_WALL_SIGN = REGISTRY.register("magenta_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_HANGING_SIGN = REGISTRY.register("magenta_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> MAGENTA_METAL_WALL_HANGING_SIGN = REGISTRY.register("magenta_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.MAGENTA_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_SIGN = REGISTRY.register("orange_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_WALL_SIGN = REGISTRY.register("orange_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_HANGING_SIGN = REGISTRY.register("orange_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> ORANGE_METAL_WALL_HANGING_SIGN = REGISTRY.register("orange_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.ORANGE_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_SIGN = REGISTRY.register("pink_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_WALL_SIGN = REGISTRY.register("pink_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_HANGING_SIGN = REGISTRY.register("pink_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PINK_METAL_WALL_HANGING_SIGN = REGISTRY.register("pink_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PINK_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_SIGN = REGISTRY.register("purple_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_WALL_SIGN = REGISTRY.register("purple_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_HANGING_SIGN = REGISTRY.register("purple_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> PURPLE_METAL_WALL_HANGING_SIGN = REGISTRY.register("purple_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.PURPLE_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_SIGN = REGISTRY.register("red_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_WALL_SIGN = REGISTRY.register("red_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_HANGING_SIGN = REGISTRY.register("red_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> RED_METAL_WALL_HANGING_SIGN = REGISTRY.register("red_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.RED_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_SIGN = REGISTRY.register("white_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_WALL_SIGN = REGISTRY.register("white_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_HANGING_SIGN = REGISTRY.register("white_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> WHITE_METAL_WALL_HANGING_SIGN = REGISTRY.register("white_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.WHITE_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_SIGN = REGISTRY.register("yellow_metal_sign", () -> new MetalSignBlock(METAL_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_WALL_SIGN = REGISTRY.register("yellow_metal_wall_sign", () -> new MetalWallSignBlock(METAL_WALL_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_HANGING_SIGN = REGISTRY.register("yellow_metal_hanging_sign", () -> new MetalHangingSignBlock(METAL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	public static final DeferredBlock<Block> YELLOW_METAL_WALL_HANGING_SIGN = REGISTRY.register("yellow_metal_wall_hanging_sign", () -> new MetalWallHangingSignBlock(METAL_WALL_HANGING_SIGN_PROPERTIES, BetterToolsModWoodTypes.YELLOW_METAL_SIGN));
	// End of user code block custom blocks
}